[workspace]
resolver = "2"
members = [
  "crates/kamn-agent-lib",
  "crates/kamn-cli",
  "crates/kamn-core",
  "crates/kamn-kolme",
  "crates/kamn-mcp-server",
  "crates/kamn-sdk",
  "crates/kamn-node",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.1.0"

[workspace.lints.clippy]
unwrap_used = "deny"
