pub(crate) const SERVICE_API_ROUTE_AUTHZ_MATRIX_ROWS: &[(&str, &str, &str, bool, &str)] = &[
    ("GET", "/healthz", "", false, "HTTP/1.1 200 OK"),
    ("GET", "/metrics", "", false, "HTTP/1.1 200 OK"),
    (
        "POST",
        "/v1/messages/send",
        "{\"message\":\"matrix-message\"}",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "POST",
        "/v1/channels/create",
        "{\"name\":\"matrix-channel\"}",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "POST",
        "/v1/tasks/create",
        "{\"task\":\"matrix-task\"}",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "POST",
        "/v1/agents/search",
        "{\"capability\":\"code\"}",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "POST",
        "/v1/tasks/task-matrix/accept",
        "{}",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "POST",
        "/v1/tasks/task-matrix/complete",
        "{}",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "POST",
        "/v1/escrow/fund",
        "{\"task_id\":\"task-matrix\",\"amount\":100}",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "POST",
        "/v1/escrow/escrow-matrix/release",
        "{}",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "POST",
        "/v1/content/register",
        "{\"content\":\"matrix-content\",\"retention_class\":\"standard\"}",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "POST",
        "/v1/content/content-matrix/expire",
        "{}",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "POST",
        "/v1/content/content-matrix/tombstone",
        "{}",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "GET",
        "/v1/content/content-matrix",
        "",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "POST",
        "/v1/bridge/submit",
        "{\"source_message_id\":\"msg-matrix\",\"target_network\":\"testnet\"}",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "POST",
        "/v1/bridge/bridge-matrix/forward",
        "{}",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "GET",
        "/v1/bridge/bridge-matrix",
        "",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "GET",
        "/v1/messages/msg-matrix",
        "",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "GET",
        "/v1/channels/channel-matrix/messages",
        "",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "GET",
        "/v1/tasks/task-matrix",
        "",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "POST",
        "/v1/agents/register",
        "{\"agent_type\":\"assistant\",\"model_family\":\"gpt-5\",\"capabilities\":[\"text\"]}",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "GET",
        "/v1/agents/kamn:did:agent:matrix",
        "",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "GET",
        "/v1/agents/kamn:did:agent:matrix/balance",
        "",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
    (
        "GET",
        "/v1/events/ws",
        "",
        true,
        "HTTP/1.1 401 Unauthorized",
    ),
];
