use super::{
    DiagnosticsMode, LocalProfile, NodeCli, NodeRole, OutputMode, PeerLifecycleEvent,
    ProposalCandidate, RejoinAttempt, RuntimeMode, SyncMode,
    DEFAULT_OBSERVABILITY_ENDPOINT_HEALTH_PATH, DEFAULT_OBSERVABILITY_ENDPOINT_IDLE_TIMEOUT_MS,
    DEFAULT_OBSERVABILITY_ENDPOINT_MAX_REQUESTS, DEFAULT_OBSERVABILITY_ENDPOINT_METRICS_PATH,
    DEFAULT_SERVICE_API_BODY_LIMIT_BYTES, DEFAULT_SERVICE_API_CONCURRENCY_LIMIT,
    DEFAULT_SERVICE_API_IDLE_TIMEOUT_MS, DEFAULT_SERVICE_API_MAX_REQUESTS,
    DEFAULT_SERVICE_API_RATE_LIMIT_PER_SECOND,
};

pub(super) struct CliParseState {
    pub(super) profile: Option<LocalProfile>,
    pub(super) role: Option<NodeRole>,
    pub(super) chain_id: String,
    pub(super) chain_version: String,
    pub(super) storage_dir: String,
    pub(super) enable_gossip: bool,
    pub(super) sync_mode: SyncMode,
    pub(super) runtime_mode: RuntimeMode,
    pub(super) expected_state_version: Option<u64>,
    pub(super) expected_state_hash: Option<String>,
    pub(super) proposals: Vec<ProposalCandidate>,
    pub(super) rejoin_attempts: Vec<RejoinAttempt>,
    pub(super) daemon_max_ticks: Option<u64>,
    pub(super) daemon_tick_interval_ms: Option<u64>,
    pub(super) daemon_shutdown_signal_ticks: Vec<u64>,
    pub(super) daemon_shutdown_os_signals: bool,
    pub(super) daemon_shutdown_drain_ticks: Option<u64>,
    pub(super) daemon_shutdown_timeout_ticks: Option<u64>,
    pub(super) daemon_peer_id: Option<String>,
    pub(super) daemon_lifecycle_events: Vec<PeerLifecycleEvent>,
    pub(super) kolme_live_base_url: Option<String>,
    pub(super) kolme_live_provider_hint: Option<String>,
    pub(super) kolme_live_signing_profile: Option<String>,
    pub(super) kolme_live_strict_signer_contracts: bool,
    pub(super) kolme_live_signer_profile: Option<String>,
    pub(super) kolme_live_signer_key_source: Option<String>,
    pub(super) api_bind_addr: Option<String>,
    pub(super) api_max_requests: u64,
    pub(super) api_idle_timeout_ms: u64,
    pub(super) api_body_limit_bytes: u64,
    pub(super) api_concurrency_limit: u64,
    pub(super) api_rate_limit_per_second: u64,
    pub(super) observability_endpoint_bind_addr: Option<String>,
    pub(super) observability_endpoint_metrics_path: String,
    pub(super) observability_endpoint_health_path: String,
    pub(super) observability_endpoint_max_requests: u64,
    pub(super) observability_endpoint_idle_timeout_ms: u64,
    pub(super) output_mode: OutputMode,
    pub(super) diagnostics_mode: DiagnosticsMode,
    pub(super) observability_endpoint_metrics_path_overridden: bool,
    pub(super) observability_endpoint_health_path_overridden: bool,
    pub(super) observability_endpoint_max_requests_overridden: bool,
    pub(super) observability_endpoint_idle_timeout_ms_overridden: bool,
    pub(super) api_max_requests_overridden: bool,
    pub(super) api_idle_timeout_ms_overridden: bool,
    pub(super) api_body_limit_bytes_overridden: bool,
    pub(super) api_concurrency_limit_overridden: bool,
    pub(super) api_rate_limit_per_second_overridden: bool,
    pub(super) role_overridden: bool,
    pub(super) chain_id_overridden: bool,
    pub(super) chain_version_overridden: bool,
    pub(super) storage_dir_overridden: bool,
    pub(super) gossip_overridden: bool,
    pub(super) sync_mode_overridden: bool,
}

impl CliParseState {
    pub(super) fn new() -> Self {
        Self {
            profile: None,
            role: None,
            chain_id: String::from("kamn-devnet"),
            chain_version: String::from("v0.1.0"),
            storage_dir: String::from("./data"),
            enable_gossip: true,
            sync_mode: SyncMode::Fast,
            runtime_mode: RuntimeMode::bootstrap(),
            expected_state_version: None,
            expected_state_hash: None,
            proposals: Vec::new(),
            rejoin_attempts: Vec::new(),
            daemon_max_ticks: None,
            daemon_tick_interval_ms: None,
            daemon_shutdown_signal_ticks: Vec::new(),
            daemon_shutdown_os_signals: false,
            daemon_shutdown_drain_ticks: None,
            daemon_shutdown_timeout_ticks: None,
            daemon_peer_id: None,
            daemon_lifecycle_events: Vec::new(),
            kolme_live_base_url: None,
            kolme_live_provider_hint: None,
            kolme_live_signing_profile: None,
            kolme_live_strict_signer_contracts: false,
            kolme_live_signer_profile: None,
            kolme_live_signer_key_source: None,
            api_bind_addr: None,
            api_max_requests: DEFAULT_SERVICE_API_MAX_REQUESTS,
            api_idle_timeout_ms: DEFAULT_SERVICE_API_IDLE_TIMEOUT_MS,
            api_body_limit_bytes: DEFAULT_SERVICE_API_BODY_LIMIT_BYTES,
            api_concurrency_limit: DEFAULT_SERVICE_API_CONCURRENCY_LIMIT,
            api_rate_limit_per_second: DEFAULT_SERVICE_API_RATE_LIMIT_PER_SECOND,
            observability_endpoint_bind_addr: None,
            observability_endpoint_metrics_path: DEFAULT_OBSERVABILITY_ENDPOINT_METRICS_PATH
                .to_owned(),
            observability_endpoint_health_path: DEFAULT_OBSERVABILITY_ENDPOINT_HEALTH_PATH
                .to_owned(),
            observability_endpoint_max_requests: DEFAULT_OBSERVABILITY_ENDPOINT_MAX_REQUESTS,
            observability_endpoint_idle_timeout_ms: DEFAULT_OBSERVABILITY_ENDPOINT_IDLE_TIMEOUT_MS,
            output_mode: OutputMode::text(),
            diagnostics_mode: DiagnosticsMode::basic(),
            observability_endpoint_metrics_path_overridden: false,
            observability_endpoint_health_path_overridden: false,
            observability_endpoint_max_requests_overridden: false,
            observability_endpoint_idle_timeout_ms_overridden: false,
            api_max_requests_overridden: false,
            api_idle_timeout_ms_overridden: false,
            api_body_limit_bytes_overridden: false,
            api_concurrency_limit_overridden: false,
            api_rate_limit_per_second_overridden: false,
            role_overridden: false,
            chain_id_overridden: false,
            chain_version_overridden: false,
            storage_dir_overridden: false,
            gossip_overridden: false,
            sync_mode_overridden: false,
        }
    }

    pub(super) fn into_node_cli(self, role: NodeRole) -> NodeCli {
        NodeCli {
            profile: self.profile,
            role,
            chain_id: self.chain_id,
            chain_version: self.chain_version,
            storage_dir: self.storage_dir,
            enable_gossip: self.enable_gossip,
            sync_mode: self.sync_mode,
            runtime_mode: self.runtime_mode,
            expected_state_version: self.expected_state_version,
            expected_state_hash: self.expected_state_hash,
            proposals: self.proposals,
            rejoin_attempts: self.rejoin_attempts,
            daemon_max_ticks: self.daemon_max_ticks,
            daemon_tick_interval_ms: self.daemon_tick_interval_ms,
            daemon_shutdown_signal_ticks: self.daemon_shutdown_signal_ticks,
            daemon_shutdown_os_signals: self.daemon_shutdown_os_signals,
            daemon_shutdown_drain_ticks: self.daemon_shutdown_drain_ticks,
            daemon_shutdown_timeout_ticks: self.daemon_shutdown_timeout_ticks,
            daemon_peer_id: self.daemon_peer_id,
            daemon_lifecycle_events: self.daemon_lifecycle_events,
            kolme_live_base_url: self.kolme_live_base_url,
            kolme_live_provider_hint: self.kolme_live_provider_hint,
            kolme_live_signing_profile: self.kolme_live_signing_profile,
            kolme_live_strict_signer_contracts: self.kolme_live_strict_signer_contracts,
            kolme_live_signer_profile: self.kolme_live_signer_profile,
            kolme_live_signer_key_source: self.kolme_live_signer_key_source,
            api_bind_addr: self.api_bind_addr,
            api_max_requests: self.api_max_requests,
            api_idle_timeout_ms: self.api_idle_timeout_ms,
            api_body_limit_bytes: self.api_body_limit_bytes,
            api_concurrency_limit: self.api_concurrency_limit,
            api_rate_limit_per_second: self.api_rate_limit_per_second,
            observability_endpoint_bind_addr: self.observability_endpoint_bind_addr,
            observability_endpoint_metrics_path: self.observability_endpoint_metrics_path,
            observability_endpoint_health_path: self.observability_endpoint_health_path,
            observability_endpoint_max_requests: self.observability_endpoint_max_requests,
            observability_endpoint_idle_timeout_ms: self.observability_endpoint_idle_timeout_ms,
            output_mode: self.output_mode,
            diagnostics_mode: self.diagnostics_mode,
        }
    }
}
