use super::*;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct NodeCli {
    pub(crate) profile: Option<LocalProfile>,
    pub(crate) role: NodeRole,
    pub(crate) chain_id: String,
    pub(crate) chain_version: String,
    pub(crate) storage_dir: String,
    pub(crate) enable_gossip: bool,
    pub(crate) sync_mode: SyncMode,
    pub(crate) runtime_mode: RuntimeMode,
    pub(crate) expected_state_version: Option<u64>,
    pub(crate) expected_state_hash: Option<String>,
    pub(crate) proposals: Vec<ProposalCandidate>,
    pub(crate) rejoin_attempts: Vec<RejoinAttempt>,
    pub(crate) daemon_max_ticks: Option<u64>,
    pub(crate) daemon_tick_interval_ms: Option<u64>,
    pub(crate) daemon_shutdown_signal_ticks: Vec<u64>,
    pub(crate) daemon_shutdown_os_signals: bool,
    pub(crate) daemon_shutdown_drain_ticks: Option<u64>,
    pub(crate) daemon_shutdown_timeout_ticks: Option<u64>,
    pub(crate) daemon_peer_id: Option<String>,
    pub(crate) daemon_lifecycle_events: Vec<PeerLifecycleEvent>,
    pub(crate) kolme_live_base_url: Option<String>,
    pub(crate) kolme_live_provider_hint: Option<String>,
    pub(crate) kolme_live_signing_profile: Option<String>,
    pub(crate) kolme_live_strict_signer_contracts: bool,
    pub(crate) kolme_live_signer_profile: Option<String>,
    pub(crate) kolme_live_signer_key_source: Option<String>,
    pub(crate) api_bind_addr: Option<String>,
    pub(crate) api_max_requests: u64,
    pub(crate) api_idle_timeout_ms: u64,
    pub(crate) api_body_limit_bytes: u64,
    pub(crate) api_concurrency_limit: u64,
    pub(crate) api_rate_limit_per_second: u64,
    pub(crate) observability_endpoint_bind_addr: Option<String>,
    pub(crate) observability_endpoint_metrics_path: String,
    pub(crate) observability_endpoint_health_path: String,
    pub(crate) observability_endpoint_max_requests: u64,
    pub(crate) observability_endpoint_idle_timeout_ms: u64,
    pub(crate) output_mode: OutputMode,
    pub(crate) diagnostics_mode: DiagnosticsMode,
}
