[package]
name = "kamn-sdk"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
kamn-core = { path = "../kamn-core" }
kamn-types = { path = "../kamn-types" }
serde_json.workspace = true
rustls = { workspace = true, features = ["ring", "std", "tls12"] }
rustls-pemfile.workspace = true
webpki-roots.workspace = true

[lints]
workspace = true
