#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
README_FILE="$ROOT_DIR/README.md"

if [ ! -f "$README_FILE" ]; then
  echo "README contract failed: README.md is missing at repository root." >&2
  exit 1
fi

required_headers=(
  "# KAMN"
  "## What This Repository Contains"
  "## Quickstart"
  "## Workflow"
  "## Key Links"
)

for header in "${required_headers[@]}"; do
  if ! grep -Fq "$header" "$README_FILE"; then
    echo "README contract failed: missing header '$header'." >&2
    exit 1
  fi
done

required_snippets=(
  "cargo fmt --check"
  "cargo clippy -- -D warnings"
  "cargo test"
  "make smoke-live-network"
  "live-network-smoke-report.json"
  "make deep-live-network"
  "live-network-pilot-report.json"
  "make demo"
  "make demo-localhost-transport"
  "make ci-tools"
  "generate_test_harness_loc_report.sh --output-json /tmp/test-harness-loc-report.json"
  "check_test_harness_loc_soft_budget.sh --report-file /tmp/test-harness-loc-report.json --budget-file .ci/test-harness-loc-soft-budget.env --baseline-file .ci/test-harness-loc-baseline.env --output-json /tmp/test-harness-loc-soft-budget-report.json"
  "soft_budget_status=exceeded"
  "review_required=true"
  "test_makefile_execution_contract.sh"
  "run_localhost_signed_demo.sh"
  "run_localhost_signed_demo.sh --help"
  "--timeout-seconds"
  "run_localhost_signed_integration_harness.sh --scenario signature-mismatch"
  "run_localhost_signed_integration_contract_lane.sh"
  "kamn.sdk.localhost-signed.integration-contract.v1"
  "run_localhost_signed_integration_contract_lane_tests"
  "check_localhost_signed_integration_evidence_policy.sh --report-file"
  "run_live_transport_replay_tamper_fast_lane.sh --output-report /tmp/live-transport-replay-tamper-fast-report.json"
  "check_live_transport_replay_tamper_policy.sh --bundle-file /tmp/live-transport-replay-tamper-fast-report.json"
  "signature_mismatch_detected"
  "session_expired_detected"
  "tamper_payload_detected"
  "docs/foundation/runtime-network.md#live-transport-demo-failure-taxonomy-and-troubleshooting"
  "docs/planning/live-network-wave.md#troubleshooting-runbook"
  "check_kamn_core_missing_docs_policy.sh"
  "/tmp/localhost-signed-integration-contract-report.json"
  "run_localhost_bridge_demo_evidence_contract_lane.sh"
  "run_localhost_bridge_demo_evidence_deep_lane.sh"
  "kamn.bridge.localhost-demo-evidence.v1"
  "check_runtime_commit_decomposition_parity_matrix.py check --matrix-file fixtures/kolme_compatibility/runtime_commit_decomposition_parity_matrix.json"
  "test_check_runtime_commit_decomposition_parity_matrix.sh"
  "docs/foundation/kolme-runtime-commit-client.md"
  "run_local_fork_sync_metadata_lane.sh --mode dry-run"
  "run_local_fork_sync_metadata_lane.sh --mode run"
  "kamn.kolme.local-fork-sync-metadata-summary.v1"
  "run_local_fork_smoke_evidence_lane.sh --mode dry-run"
  "run_local_fork_smoke_evidence_lane.sh --mode run"
  "kamn.kolme.local-fork-smoke-evidence-summary.v1"
  "run_local_kolme_api_probe_lane.sh --mode dry-run"
  "run_local_kolme_api_probe_lane.sh --mode run"
  "--fork-chain-version v0.15.2"
  "kamn.kolme.local-api-probe-summary.v1"
  "run_local_kolme_api_smoke_lane.sh --mode dry-run"
  "run_local_kolme_api_smoke_lane.sh --mode run"
  "kamn.kolme.local-api-smoke-summary.v1"
  "run_local_kolme_live_api_conformance_harness.sh --mode dry-run"
  "run_local_kolme_live_api_conformance_harness.sh --mode run"
  "check_local_kolme_live_api_conformance_policy.py --report-file /tmp/kolme-local-live-api-conformance-summary.json"
  "run_local_kolme_live_api_conformance_contract_lane.sh --output-json /tmp/kolme-local-live-api-conformance-summary.json --policy-output-json /tmp/kolme-local-live-api-conformance-policy.json"
  "kamn.kolme.local-live-api-conformance-summary.v1"
  "run_local_kolme_fork_bootstrap_readiness_lane.sh --mode dry-run"
  "run_local_kolme_fork_bootstrap_readiness_lane.sh --mode run"
  "check_local_kolme_fork_bootstrap_readiness_policy.py --report-file /tmp/kolme-local-fork-bootstrap-readiness-summary.json"
  "run_local_kolme_fork_bootstrap_readiness_contract_lane.sh --output-json /tmp/kolme-local-fork-bootstrap-readiness-summary.json --policy-output-json /tmp/kolme-local-fork-bootstrap-readiness-policy.json"
  "kamn.kolme.local-fork-bootstrap-readiness-summary.v1"
  "run_local_kamn_live_runtime_integration_lane.sh --mode dry-run"
  "run_local_kamn_live_runtime_integration_lane.sh --mode run"
  "--runtime-profile real-node"
  "check_local_kamn_live_runtime_integration_policy.py --report-file /tmp/kolme-local-kamn-live-runtime-integration-summary.json"
  "check_local_kamn_live_runtime_real_node_profile_policy.py --report-file /tmp/kolme-local-kamn-live-runtime-integration-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code dry_run_no_commands_executed --require-non-synthetic-run-evidence --output-json /tmp/kolme-local-kamn-live-runtime-real-node-policy.json"
  "runtime_commit_command_profile=real-node-non-synthetic-v1"
  "runtime_commit_policy_command_profile=real-node-non-synthetic-v1"
  "runtime_commit_command_profile_version=v1"
  "runtime_commit_command_profile_mismatch"
  "runtime_commit_non_synthetic_submit_probe_missing"
  "integration_kolme_fork_live_node_submit_reaches_endpoint"
  "run_local_kamn_live_runtime_real_node_profile_contract_lane.sh --output-json /tmp/kolme-local-kamn-live-runtime-integration-summary.json --policy-output-json /tmp/kolme-local-kamn-live-runtime-real-node-policy.json"
  "real-node strict runtime evidence checker remains local-only and excluded from ci-fast-gate."
  "run_local_kamn_live_runtime_integration_contract_lane.sh --output-json /tmp/kolme-local-kamn-live-runtime-integration-summary.json --policy-output-json /tmp/kolme-local-kamn-live-runtime-integration-policy.json"
  "kamn.kolme.local-kamn-live-runtime-integration-summary.v1"
  "run_local_kolme_fork_process_lifecycle_lane.sh --mode dry-run"
  "run_local_kolme_fork_process_lifecycle_lane.sh --mode run"
  "check_local_kolme_fork_process_lifecycle_policy.py --report-file /tmp/kolme-local-fork-process-lifecycle-summary.json"
  "run_local_kolme_fork_process_lifecycle_contract_lane.sh --output-json /tmp/kolme-local-fork-process-lifecycle-summary.json --policy-output-json /tmp/kolme-local-fork-process-lifecycle-policy.json"
  "kamn.kolme.local-fork-process-lifecycle-summary.v1"
  "run_local_kolme_fork_profile_preflight_lane.sh --mode dry-run"
  "check_local_kolme_fork_profile_preflight_policy.py --report-file /tmp/kolme-local-fork-profile-preflight-summary.json"
  "run_local_kolme_fork_profile_preflight_contract_lane.sh --output-json /tmp/kolme-local-fork-profile-preflight-summary.json --policy-output-json /tmp/kolme-local-fork-profile-preflight-policy.json"
  "kamn.kolme.local-fork-profile-preflight-policy-report.v1"
  "kamn.kolme.local-fork-profile-preflight-summary.v1"
  "run_local_kolme_fork_self_test_lane.sh --mode dry-run"
  "--matrix-cargo-profile portable"
  "check_local_kolme_fork_self_test_policy.py --report-file /tmp/kolme-local-fork-self-test-summary.json"
  "run_local_kolme_fork_self_test_contract_lane.sh --output-json /tmp/kolme-local-fork-self-test-summary.json --policy-output-json /tmp/kolme-local-fork-self-test-policy.json"
  "kamn.kolme.local-fork-self-test-summary.v1"
  "kamn.kolme.local-fork-self-test-policy-report.v1"
  "run_local_kolme_fork_portability_preflight_lane.sh --mode dry-run"
  "check_local_kolme_fork_portability_preflight_policy.py --report-file /tmp/kolme-local-fork-portability-preflight-summary.json"
  "run_local_kolme_fork_portability_preflight_contract_lane.sh --output-json /tmp/kolme-local-fork-portability-preflight-summary.json --policy-output-json /tmp/kolme-local-fork-portability-preflight-policy.json"
  "kamn.kolme.local-fork-portability-preflight-summary.v1"
  "kamn.kolme.local-fork-portability-preflight-policy-report.v1"
  "run_local_bootstrap_health_checks.sh --mode dry-run"
  "check_local_bootstrap_health_policy.py --report-file /tmp/kolme-local-bootstrap-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code dry_run_no_commands_executed --output-json /tmp/kolme-local-bootstrap-policy.json"
  "run_local_bootstrap_health_checks_contract_lane.sh --output-json /tmp/kolme-local-bootstrap-summary.json --policy-output-json /tmp/kolme-local-bootstrap-policy.json"
  "kamn.kolme.local-bootstrap-policy-report.v1"
  "run_local_e2e_integration_lane.sh --mode dry-run"
  "check_local_e2e_integration_policy.py --report-file /tmp/kolme-local-e2e-integration-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code dry_run_no_commands_executed --output-json /tmp/kolme-local-e2e-integration-policy.json"
  "run_local_e2e_integration_contract_lane.sh --output-json /tmp/kolme-local-e2e-integration-summary.json --policy-output-json /tmp/kolme-local-e2e-integration-policy.json"
  "kamn.kolme.local-e2e-integration-policy-report.v1"
  "run_local_heavy_validation_matrix.sh --mode dry-run --output-json /tmp/kolme-local-heavy-validation-summary.json"
  "check_local_heavy_validation_matrix_policy.py --report-file /tmp/kolme-local-heavy-validation-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code dry_run_no_commands_executed --output-json /tmp/kolme-local-heavy-validation-policy.json"
  "run_local_heavy_validation_matrix_contract_lane.sh --output-json /tmp/kolme-local-heavy-validation-summary.json --policy-output-json /tmp/kolme-local-heavy-validation-policy.json"
  "kamn.kolme.local-heavy-validation-policy-report.v1"
  "KAMN_KOLME_LOCAL_HEAVY=1"
  "--cargo-profile portable"
  "Local-only heavy Kolme run-mode commands stay excluded from ci-fast-gate"
  "scripts/kolme/test_run_local_kolme_api_smoke_lane.sh"
  "scripts/kolme/test_run_local_kolme_live_api_conformance_contract_lane.sh"
  "scripts/kolme/test_run_local_kolme_fork_bootstrap_readiness_contract_lane.sh"
  "scripts/kolme/test_run_local_kamn_live_runtime_integration_contract_lane.sh"
  "scripts/kolme/test_run_local_kolme_fork_process_lifecycle_contract_lane.sh"
  "scripts/kolme/test_run_local_kolme_fork_profile_preflight_lane.sh"
  "scripts/kolme/test_run_local_kolme_fork_profile_preflight_contract_lane.sh"
  "scripts/kolme/test_run_local_kolme_fork_self_test_lane.sh"
  "scripts/kolme/test_run_local_kolme_fork_self_test_contract_lane.sh"
  "scripts/kolme/test_run_local_kolme_fork_portability_preflight_lane.sh"
  "scripts/kolme/test_check_local_kolme_fork_portability_preflight_policy.sh"
  "scripts/kolme/test_run_local_kolme_fork_portability_preflight_contract_lane.sh"
  "scripts/kolme/test_run_local_bootstrap_health_checks.sh"
  "scripts/kolme/test_check_local_bootstrap_health_policy.sh"
  "scripts/kolme/test_run_local_bootstrap_health_checks_contract_lane.sh"
  "scripts/kolme/test_run_local_e2e_integration_lane.sh"
  "scripts/kolme/test_check_local_e2e_integration_policy.sh"
  "scripts/kolme/test_run_local_e2e_integration_contract_lane.sh"
  "scripts/kolme/test_check_local_heavy_validation_matrix_policy.sh"
  "scripts/kolme/test_run_local_heavy_validation_matrix_contract_lane.sh"
  "run_fast_gate_native_api_parity_contract_lane.sh --output-json /tmp/kolme-fast-gate-native-api-parity-summary.json"
  "check_fast_gate_native_api_parity_policy.py --report-file /tmp/kolme-fast-gate-native-api-parity-summary.json"
  "KAMN_KOLME_FAST_GATE_NATIVE_PARITY_MAX_SECONDS=120"
  "run_local_native_api_parity_live_proof_lane.sh --mode run"
  "--request PUT --data '{\\\"message\\\":\\\"native-parity\\\",\\\"signature\\\":\\\"sig\\\",\\\"recovery_id\\\":1}' http://127.0.0.1:3000/broadcast"
  "run_a2a_mcp_conformance_contract_lane.sh"
  "check_a2a_mcp_conformance_policy.sh --report-file"
  "/tmp/a2a-mcp-conformance-report.json"
  "kamn.a2a_mcp.conformance-report.v1"
  "check_settlement_reconciliation_evidence_policy.sh --bundle-file"
  "Node.js 22"
  "scripts/ci/test_select_targets.sh"
  "bash scripts/frontend/test_dashboard_package_runtime_compat.sh"
  "KAMN_DASHBOARD_NODE_BIN"
  "KAMN_DASHBOARD_FALLBACK_NODE_CMD"
  "AGENTS.md"
  "PRD.md"
  "docs/planning/engineering-hardening-wave.md"
)

for snippet in "${required_snippets[@]}"; do
  if ! grep -Fq -- "$snippet" "$README_FILE"; then
    echo "README contract failed: missing snippet '$snippet'." >&2
    exit 1
  fi
done

echo "README contract tests passed."
