#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STRATEGY_DOC="$ROOT_DIR/docs/ci/strategy.md"

if [ ! -f "$STRATEGY_DOC" ]; then
  echo "CI strategy contract failed: docs/ci/strategy.md is missing." >&2
  exit 1
fi

required_snippets=(
  "make check"
  "make test"
  "make smoke-live-network"
  "make deep-live-network"
  "make demo"
  "make demo-localhost-transport"
  "make ci-tools"
  "test_makefile_execution_contract.sh"
  "test_kolme_command_surface_coverage_contract.sh"
  "test_kolme_command_surface_asymmetry_contract.sh"
  ".ci/kolme-command-surface-asymmetry-policy.json"
  "changes map to CI contract scope"
  "unknown/full fallback remains disabled for this path"
  "run_runtime_snapshot_contract_tests=true"
  "test_scope=runtime-contract"
  "run_localhost_signed_integration_contract_lane_tests"
  "sdk-live-localhost-integration"
  "run_live_transport_replay_tamper_fast_lane.sh"
  "check_live_transport_replay_tamper_policy.sh"
  "KAMN_SDK_REPLAY_TAMPER_CONTRACT_MAX_SECONDS=60"
  "run_live_transport_parity_contract_tests=true"
  "live_transport_parity_languages=rust,python,typescript"
  "run_kolme_version_compatibility_contract_tests=true"
  "test_scope=kolme-version-contract"
  "run_local_fork_sync_metadata_lane.sh --mode run"
  "run_local_fork_smoke_evidence_lane.sh --mode run"
  "run_local_kolme_api_probe_lane.sh --mode run --base-url http://127.0.0.1:3000 --fork-chain-version v0.15.2"
  "run_local_kolme_api_smoke_lane.sh --mode run"
  "run_local_kolme_live_api_conformance_harness.sh --mode run"
  "check_local_kolme_live_api_conformance_policy.py --report-file /tmp/kolme-local-live-api-conformance-summary.json"
  "run_local_kolme_live_api_conformance_contract_lane.sh --output-json /tmp/kolme-local-live-api-conformance-summary.json --policy-output-json /tmp/kolme-local-live-api-conformance-policy.json"
  "run_local_kolme_fork_bootstrap_readiness_lane.sh --mode run"
  "check_local_kolme_fork_bootstrap_readiness_policy.py --report-file /tmp/kolme-local-fork-bootstrap-readiness-summary.json"
  "run_local_kolme_fork_bootstrap_readiness_contract_lane.sh --output-json /tmp/kolme-local-fork-bootstrap-readiness-summary.json --policy-output-json /tmp/kolme-local-fork-bootstrap-readiness-policy.json"
  "run_local_kamn_live_runtime_integration_lane.sh --mode run"
  "check_local_kamn_live_runtime_integration_policy.py --report-file /tmp/kolme-local-kamn-live-runtime-integration-summary.json"
  "run_local_kamn_live_runtime_integration_contract_lane.sh --output-json /tmp/kolme-local-kamn-live-runtime-integration-summary.json --policy-output-json /tmp/kolme-local-kamn-live-runtime-integration-policy.json"
  "run_local_kolme_fork_process_lifecycle_lane.sh --mode run"
  "check_local_kolme_fork_process_lifecycle_policy.py --report-file /tmp/kolme-local-fork-process-lifecycle-summary.json"
  "run_local_kolme_fork_process_lifecycle_contract_lane.sh --output-json /tmp/kolme-local-fork-process-lifecycle-summary.json --policy-output-json /tmp/kolme-local-fork-process-lifecycle-policy.json"
  "run_local_runtime_commit_live_lane.sh --mode run"
  "run_local_native_api_parity_live_proof_lane.sh --mode run"
  "--request PUT --data '{\\\"message\\\":\\\"native-parity\\\",\\\"signature\\\":\\\"sig\\\",\\\"recovery_id\\\":1}' http://127.0.0.1:3000/broadcast"
  "test_run_local_runtime_commit_live_lane.sh"
  "test_run_local_native_api_parity_live_proof_contract_lane.sh"
  "test_generate_fork_compatibility_evidence.sh"
  "test_check_fork_compatibility_policy.sh"
  "test_run_runtime_commit_adapter_contract_lane.sh"
  "test_run_local_kolme_fork_rust_test_matrix_lane.sh"
  "test_check_local_kolme_fork_rust_test_matrix_policy.sh"
  "test_run_local_kolme_fork_rust_test_matrix_contract_lane.sh"
  "run_local_kolme_fork_rust_test_matrix_contract_lane.sh --output-json /tmp/kolme-local-fork-rust-test-matrix-summary.json --policy-output-json /tmp/kolme-local-fork-rust-test-matrix-policy.json"
  "test_run_local_kolme_live_api_conformance_contract_lane.sh"
  "test_run_local_kolme_fork_bootstrap_readiness_contract_lane.sh"
  "test_run_local_kamn_live_runtime_integration_contract_lane.sh"
  "test_run_local_kolme_fork_process_lifecycle_contract_lane.sh"
  "test_run_local_kolme_fork_profile_preflight_contract_lane.sh"
  "test_run_fast_gate_native_api_parity_contract_lane.sh"
  "run_fast_gate_native_api_parity_contract_lane.sh --output-json /tmp/kolme-fast-gate-native-api-parity-summary.json"
  "check_fast_gate_native_api_parity_policy.py --report-file /tmp/kolme-fast-gate-native-api-parity-summary.json"
  "KAMN_KOLME_FAST_GATE_NATIVE_PARITY_MAX_SECONDS=120"
  "test_run_nonce_broadcast_parity_contract_lane.sh"
  "KAMN_KOLME_NONCE_BROADCAST_PARITY_MAX_SECONDS=60"
  "run_local_bootstrap_health_checks.sh"
  "check_local_bootstrap_health_policy.py --report-file /tmp/kolme-local-bootstrap-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code dry_run_no_commands_executed --output-json /tmp/kolme-local-bootstrap-policy.json"
  "run_local_bootstrap_health_checks_contract_lane.sh --output-json /tmp/kolme-local-bootstrap-summary.json --policy-output-json /tmp/kolme-local-bootstrap-policy.json"
  "test_check_local_bootstrap_health_policy.sh"
  "test_run_local_bootstrap_health_checks_contract_lane.sh"
  "run_local_e2e_integration_lane.sh"
  "check_local_e2e_integration_policy.py --report-file /tmp/kolme-local-e2e-integration-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code dry_run_no_commands_executed --output-json /tmp/kolme-local-e2e-integration-policy.json"
  "run_local_e2e_integration_contract_lane.sh --output-json /tmp/kolme-local-e2e-integration-summary.json --policy-output-json /tmp/kolme-local-e2e-integration-policy.json"
  "run_local_heavy_validation_matrix.sh --mode dry-run --output-json /tmp/kolme-local-heavy-validation-summary.json"
  "check_local_heavy_validation_matrix_policy.py --report-file /tmp/kolme-local-heavy-validation-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code dry_run_no_commands_executed --output-json /tmp/kolme-local-heavy-validation-policy.json"
  "run_local_heavy_validation_matrix_contract_lane.sh --output-json /tmp/kolme-local-heavy-validation-summary.json --policy-output-json /tmp/kolme-local-heavy-validation-policy.json"
  "KAMN_KOLME_LOCAL_HEAVY=1"
  "local-only heavy Kolme run-mode commands remain excluded from ci-fast-gate."
  "local-only fork sync/smoke run-mode commands remain excluded from ci-fast-gate."
  "local Kolme API probe/smoke run-mode commands remain excluded from ci-fast-gate."
  "local live API conformance harness run-mode commands remain excluded from ci-fast-gate."
  "local fork bootstrap/readiness run-mode commands remain excluded from ci-fast-gate."
  "local KAMN live runtime integration run-mode commands remain excluded from ci-fast-gate."
  "local fork process lifecycle integration run-mode commands remain excluded from ci-fast-gate."
  "local fork profile preflight run-mode commands remain excluded from ci-fast-gate."
  "check_local_kolme_fork_profile_preflight_policy.py --report-file /tmp/kolme-local-fork-profile-preflight-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code profile_preflight_passed --output-json /tmp/kolme-local-fork-profile-preflight-policy.json"
  "run_local_kolme_fork_profile_preflight_contract_lane.sh --output-json /tmp/kolme-local-fork-profile-preflight-summary.json --policy-output-json /tmp/kolme-local-fork-profile-preflight-policy.json"
  "local runtime-commit live run-mode commands remain excluded from ci-fast-gate."
  "local native API parity live-proof run-mode commands remain excluded from ci-fast-gate."
  "native parity fast/local command matrix remains synchronized across"
  "run_dashboard_contract_tests=true"
  "test_scope=frontend-contract"
  "run_frontend_dashboard_tests=true"
  "test_scope=frontend"
  "run_deploy_preflight_tests=true"
  "test_scope=deploy"
  "run_settlement_reconciliation_contract_tests=true"
  "test_scope=escrow-contract"
  "run_bridge_replay_harness=true"
  "test_scope=bridge"
  "run_localhost_signed_integration_contract_lane.sh"
  "run_backend_session_auth_freshness_contract_lane.sh"
  "run_dashboard_stale_error_budget_contract_lane.sh"
  "run_dashboard_shell_determinism_matrix_contract_lane.sh"
  "run_deployment_slo_rollback_contract_lane.sh"
  "run_settlement_reconciliation_contract_lane.sh"
  "run_bridge_adapter_conformance_contract_lane.sh"
  "run_post_cutover_slo_contract_lane.sh"
  "run_classification_redaction_contract_lane.sh"
  "run_quorum_attestation_replay_contract_lane.sh"
  "test_run_kamn_core_rustdoc_artifact_contract_lane.sh"
  "test_check_kamn_core_rustdoc_artifact_policy.sh"
  "scripts/ci/select_targets.sh"
  "Regression: #900"
  "Regression: #939"
  "Regression: #906"
  "Regression: #913"
  "Regression: #914"
  "Regression: #911"
  "Regression: #942"
  "Regression: #943"
  "Regression: #941"
  "Regression: #944"
  "Regression: #907"
  "Regression: #1386"
  "Regression: #1419"
  "Regression: #1431"
  "Regression: #1682"
  "Regression: #1687"
  "Regression: #1697"
  "Regression: #1692"
  "Regression: #1441"
  "Regression: #1451"
  "Regression: #1467"
  "Regression: #1468"
  "Regression: #1482"
  "Regression: #1483"
  "Regression: #1488"
  "Regression: #1489"
  "Regression: #1494"
  "Regression: #1462"
  "Regression: #1466"
  "Regression: #1497"
  "Regression: #1561"
  "Regression: #1565"
  "Regression: #1569"
)

for snippet in "${required_snippets[@]}"; do
  if ! grep -Fq -- "$snippet" "$STRATEGY_DOC"; then
    echo "CI strategy contract failed: missing snippet '$snippet'." >&2
    exit 1
  fi
done

echo "CI strategy contract tests passed."
