#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

bash "$ROOT_DIR/scripts/ci/test_evaluate_budget.sh"
bash "$ROOT_DIR/scripts/ci/test_run_with_retry.sh"
bash "$ROOT_DIR/scripts/ci/test_run_invariant_harness.sh"
bash "$ROOT_DIR/scripts/ci/test_run_cargo_test_with_quarantine.sh"
bash "$ROOT_DIR/scripts/ci/test_select_targets.sh"
bash "$ROOT_DIR/scripts/ci/test_check_flaky_registry.sh"
bash "$ROOT_DIR/scripts/ci/test_summarize_budget_artifacts.sh"
bash "$ROOT_DIR/scripts/ci/test_check_pr_ci_declaration.sh"
bash "$ROOT_DIR/scripts/ci/test_post_flaky_report_comment.sh"
bash "$ROOT_DIR/scripts/ci/test_sync_flaky_registry_issues.sh"
bash "$ROOT_DIR/scripts/ci/test_generate_performance_smoke_report.sh"
bash "$ROOT_DIR/scripts/ci/test_check_performance_thresholds.sh"
bash "$ROOT_DIR/scripts/ci/test_workflow_retry_policy.sh"
bash "$ROOT_DIR/scripts/ci/test_workflow_cache_policy.sh"
bash "$ROOT_DIR/scripts/ci/test_workflow_scope_policy.sh"
bash "$ROOT_DIR/scripts/ci/test_workflow_performance_policy.sh"
bash "$ROOT_DIR/scripts/frontend/test_dashboard_package.sh"
bash "$ROOT_DIR/scripts/frontend/test_dashboard_contract_lane.sh"
bash "$ROOT_DIR/scripts/sdk/test_run_rust_live_transport_contract_lane.sh"
bash "$ROOT_DIR/scripts/sdk/test_run_live_transport_parity_contract_lane.sh"
bash "$ROOT_DIR/scripts/sdk/test_run_transport_profile_parity_matrix.sh"
bash "$ROOT_DIR/scripts/signer/test_run_signer_emulator_contract_lane.sh"
bash "$ROOT_DIR/scripts/did/test_run_did_registry_contract_lane.sh"
bash "$ROOT_DIR/scripts/runtime/test_run_runtime_snapshot_contract_lane.sh"
bash "$ROOT_DIR/scripts/message/test_run_message_lifecycle_contract_lane.sh"
bash "$ROOT_DIR/scripts/channel/test_run_channel_lifecycle_contract_lane.sh"
bash "$ROOT_DIR/scripts/task/test_run_task_operation_snapshot_contract_lane.sh"
bash "$ROOT_DIR/scripts/canary/test_run_launch_canary_matrix.sh"
bash "$ROOT_DIR/scripts/canary/test_run_launch_canary_contract_lane.sh"
bash "$ROOT_DIR/scripts/canary/test_generate_post_cutover_slo_evidence_bundle.sh"
bash "$ROOT_DIR/scripts/canary/test_run_post_cutover_slo_contract_lane.sh"
bash "$ROOT_DIR/scripts/cutover/test_validate_mainnet_cutover_manifest.sh"
bash "$ROOT_DIR/scripts/cutover/test_run_mainnet_cutover_contract_lane.sh"
bash "$ROOT_DIR/scripts/cutover/test_generate_cutover_rollback_evidence_bundle.sh"
bash "$ROOT_DIR/scripts/cutover/test_run_cutover_rollback_contract_lane.sh"
bash "$ROOT_DIR/scripts/escrow/test_generate_settlement_reconciliation_evidence_bundle.sh"
bash "$ROOT_DIR/scripts/escrow/test_run_settlement_reconciliation_contract_lane.sh"
bash "$ROOT_DIR/scripts/escrow/test_run_settlement_reconciliation_race_matrix.sh"
bash "$ROOT_DIR/scripts/reputation/test_generate_reputation_dispute_evidence_bundle.sh"
bash "$ROOT_DIR/scripts/reputation/test_run_reputation_dispute_contract_lane.sh"
bash "$ROOT_DIR/scripts/reputation/test_run_reputation_dispute_matrix.sh"
bash "$ROOT_DIR/scripts/reputation/test_run_reputation_dispute_deep_lane.sh"
bash "$ROOT_DIR/scripts/token/test_generate_token_launch_handoff_evidence_bundle.sh"
bash "$ROOT_DIR/scripts/token/test_run_token_launch_handoff_contract_lane.sh"
bash "$ROOT_DIR/scripts/token/test_run_token_launch_handoff_deep_lane.sh"
bash "$ROOT_DIR/scripts/treasury/test_generate_treasury_disbursement_evidence_bundle.sh"
bash "$ROOT_DIR/scripts/treasury/test_run_treasury_disbursement_contract_lane.sh"
bash "$ROOT_DIR/scripts/guard/test_run_durable_guard_recovery_contract_lane.sh"
bash "$ROOT_DIR/scripts/bridge/test_run_bridge_replay_matrix.sh"
bash "$ROOT_DIR/scripts/bridge/test_run_bridge_credential_redaction_check.sh"
bash "$ROOT_DIR/scripts/bridge/test_run_bridge_credentialed_contract_lane.sh"
bash "$ROOT_DIR/scripts/bridge/test_run_telegram_ingress_contract_lane.sh"
bash "$ROOT_DIR/scripts/deploy/test_preflight_topology.sh"
bash "$ROOT_DIR/scripts/deploy/test_generate_bundle.sh"
bash "$ROOT_DIR/scripts/deploy/test_generate_gonogo_evidence_bundle.sh"
bash "$ROOT_DIR/scripts/deploy/test_run_gonogo_evidence_contract_lane.sh"
bash "$ROOT_DIR/scripts/deploy/test_generate_staging_rehearsal_bundle.sh"
bash "$ROOT_DIR/scripts/deploy/test_run_staging_rehearsal_contract_lane.sh"
bash "$ROOT_DIR/scripts/deploy/test_generate_dr_evidence_bundle.sh"
bash "$ROOT_DIR/scripts/deploy/test_run_dr_evidence_contract_lane.sh"

echo "All CI tool regression tests passed."
