#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

bash "$ROOT_DIR/scripts/ci/test_evaluate_budget.sh"
bash "$ROOT_DIR/scripts/ci/test_run_with_retry.sh"
bash "$ROOT_DIR/scripts/ci/test_run_invariant_harness.sh"
bash "$ROOT_DIR/scripts/ci/test_run_cargo_test_with_quarantine.sh"
bash "$ROOT_DIR/scripts/ci/test_select_targets.sh"
bash "$ROOT_DIR/scripts/ci/test_check_flaky_registry.sh"
bash "$ROOT_DIR/scripts/ci/test_summarize_budget_artifacts.sh"
bash "$ROOT_DIR/scripts/ci/test_check_pr_ci_declaration.sh"
bash "$ROOT_DIR/scripts/ci/test_post_flaky_report_comment.sh"
bash "$ROOT_DIR/scripts/ci/test_sync_flaky_registry_issues.sh"
bash "$ROOT_DIR/scripts/ci/test_generate_performance_smoke_report.sh"
bash "$ROOT_DIR/scripts/ci/test_check_performance_thresholds.sh"
bash "$ROOT_DIR/scripts/ci/test_workflow_retry_policy.sh"
bash "$ROOT_DIR/scripts/ci/test_workflow_cache_policy.sh"
bash "$ROOT_DIR/scripts/ci/test_workflow_scope_policy.sh"
bash "$ROOT_DIR/scripts/ci/test_workflow_performance_policy.sh"
bash "$ROOT_DIR/scripts/frontend/test_dashboard_package.sh"
bash "$ROOT_DIR/scripts/frontend/test_dashboard_contract_lane.sh"
bash "$ROOT_DIR/scripts/sdk/test_run_rust_live_transport_contract_lane.sh"
bash "$ROOT_DIR/scripts/sdk/test_run_live_transport_parity_contract_lane.sh"
bash "$ROOT_DIR/scripts/signer/test_run_signer_emulator_contract_lane.sh"
bash "$ROOT_DIR/scripts/runtime/test_run_runtime_snapshot_contract_lane.sh"
bash "$ROOT_DIR/scripts/message/test_run_message_lifecycle_contract_lane.sh"
bash "$ROOT_DIR/scripts/bridge/test_run_bridge_replay_matrix.sh"
bash "$ROOT_DIR/scripts/bridge/test_run_bridge_credential_redaction_check.sh"
bash "$ROOT_DIR/scripts/bridge/test_run_bridge_credentialed_contract_lane.sh"
bash "$ROOT_DIR/scripts/bridge/test_run_telegram_ingress_contract_lane.sh"
bash "$ROOT_DIR/scripts/deploy/test_preflight_topology.sh"
bash "$ROOT_DIR/scripts/deploy/test_generate_bundle.sh"
bash "$ROOT_DIR/scripts/deploy/test_generate_gonogo_evidence_bundle.sh"
bash "$ROOT_DIR/scripts/deploy/test_run_gonogo_evidence_contract_lane.sh"
bash "$ROOT_DIR/scripts/deploy/test_generate_staging_rehearsal_bundle.sh"
bash "$ROOT_DIR/scripts/deploy/test_run_staging_rehearsal_contract_lane.sh"
bash "$ROOT_DIR/scripts/deploy/test_generate_dr_evidence_bundle.sh"
bash "$ROOT_DIR/scripts/deploy/test_run_dr_evidence_contract_lane.sh"

echo "All CI tool regression tests passed."
