#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STRATEGY_DOC="${KAMN_CI_STRATEGY_DOC_FILE:-$ROOT_DIR/docs/ci/strategy.md}"
WAVE_RANGE_MARKER_PATTERN='non_kolme_wrapper_family_wave_range=[0-9]+-[0-9]+'

if [ ! -f "$STRATEGY_DOC" ]; then
  echo "CI strategy contract failed: docs/ci/strategy.md is missing." >&2
  exit 1
fi

mapfile -t wave_range_markers < <(grep -Eo "$WAVE_RANGE_MARKER_PATTERN" "$STRATEGY_DOC" | sort -u)
if [ "${#wave_range_markers[@]}" -ne 1 ]; then
  echo "CI strategy contract failed: expected exactly one non_kolme_wrapper_family_wave_range marker." >&2
  exit 1
fi
wave_range_marker="${wave_range_markers[0]}"
if [[ ! "$wave_range_marker" =~ ^non_kolme_wrapper_family_wave_range=([0-9]+)-([0-9]+)$ ]]; then
  echo "CI strategy contract failed: invalid non_kolme_wrapper_family_wave_range marker '$wave_range_marker'." >&2
  exit 1
fi
wave_start="${BASH_REMATCH[1]}"
wave_end="${BASH_REMATCH[2]}"
if (( wave_start < 1 || wave_end < wave_start )); then
  echo "CI strategy contract failed: unsupported non_kolme_wrapper_family_wave_range marker '$wave_range_marker'." >&2
  exit 1
fi

required_snippets=(
  "make check"
  "make test"
  "make smoke-live-network"
  "make deep-live-network"
  "make demo"
  "make demo-localhost-transport"
  "make ci-tools"
  "generate_test_harness_loc_report.sh --output-json /tmp/test-harness-loc-report.json"
  "check_test_harness_loc_soft_budget.sh --report-file /tmp/test-harness-loc-report.json --budget-file .ci/test-harness-loc-soft-budget.env --baseline-file .ci/test-harness-loc-baseline.env --trend-threshold-file .ci/test-harness-loc-trend-thresholds.env --output-json /tmp/test-harness-loc-soft-budget-report.json"
  ".ci/test-harness-loc-trend-thresholds.env"
  "run_test_harness_loc_soft_budget_contract_lane.sh --output-json /tmp/test-harness-loc-soft-budget-contract-report.json"
  "soft_budget_status=exceeded"
  "review_required=true"
  "run_kolme_test_harness_loc_soft_budget_contract_lane.sh --output-json /tmp/kolme-test-harness-loc-soft-budget-contract-report.json"
  "test_run_kolme_test_harness_loc_soft_budget_contract_lane.sh"
  "local_heavy_sensitive_drift_detected"
  "rehearsal_runbook_contract_parity_status=verified"
  "rehearsal_boundary_thresholds_schema_version=kamn.release.staging-rehearsal-boundary-thresholds.v1"
  "rehearsal_boundary_reason_taxonomy_status=verified"
  "rehearsal_boundary_reason_taxonomy_version=kamn.release.staging-rehearsal-boundary-reason-taxonomy.v1"
  "rehearsal_boundary_reason_codes_csv=rehearsal_boundary_ci_smoke_seconds_exceeded,rehearsal_boundary_local_heavy_opt_in_missing,rehearsal_runbook_contract_parity_mismatch"
  "rehearsal_boundary_ci_smoke_max_seconds=120"
  "rehearsal_boundary_local_heavy_max_seconds=900"
  "rehearsal_boundary_ci_smoke_seconds_exceeded"
  "rehearsal_boundary_local_heavy_opt_in_missing"
  "rehearsal_runbook_contract_parity_mismatch"
  "Regression: #4501"
  "Regression: #4502"
  "soft_overrun_status=within|exceeded"
  "delta_threshold_waiver_applied"
  "delta_threshold_violation_unwaived"
  "run_fast_gate_budget_delta_contract_lane.sh --output-json /tmp/fast-gate-budget-delta-contract-report.json"
  "test_run_fast_gate_budget_delta_contract_lane.sh"
  "test_generate_fast_gate_budget_delta_report.sh"
  "test_check_fast_gate_budget_delta_threshold.sh"
  "reason_codes=fast_gate_delta_threshold_file_stale"
  "reason_codes=fast_gate_delta_threshold_file_corrupt"
  "refresh .ci/fast-gate-budget-delta.env baseline and threshold metadata"
  "test_generate_test_harness_loc_report.sh"
  "test_check_test_harness_loc_soft_budget.sh"
  "test_run_test_harness_loc_soft_budget_contract_lane.sh"
  "test_harness_loc_soft_budget_contract_warn_decision=WARN"
  "test_harness_loc_soft_budget_contract_fail_decision=NO-GO"
  "reason_codes=harness_script_count_trend_warn_delta_exceeded"
  "reason_codes=harness_shell_line_total_trend_warn_delta_exceeded"
  "reason_codes=harness_script_count_trend_fail_delta_exceeded"
  "reason_codes=harness_shell_line_total_trend_fail_delta_exceeded"
  "test_makefile_execution_contract.sh"
  "test_kolme_command_surface_coverage_contract.sh"
  "test_kolme_command_surface_asymmetry_contract.sh"
  "test_run_continuous_runtime_commit_contract_lane.sh"
  "test_run_did_lifecycle_chain_adapter_contract_lane.sh"
  "test_run_message_proof_anchoring_contract_lane.sh"
  "test_run_managed_signer_startup_live_validation_contract_lane.sh"
  "test_validate_continuous_runtime_commit_live.sh"
  "test_validate_did_lifecycle_chain_adapter_live.sh"
  "test_validate_message_proof_anchoring_live.sh"
  ".ci/kolme-command-surface-asymmetry-policy.json"
  "kolme_wave10_wrapper_family_matrix.json"
  "kolme_wave10_wrapper_family_baseline.json"
  "kolme_wave10_wrapper_family_trend_thresholds.json"
  "check_kolme_wave10_wrapper_family_budget_trend.sh"
  "kolme_wave11_wrapper_family_matrix.json"
  "kolme_wave11_wrapper_family_baseline.json"
  "kolme_wave11_wrapper_family_trend_thresholds.json"
  "check_kolme_wave11_wrapper_family_budget_trend.sh"
  "non_kolme_wave_trend_test_loc_soft_budget_baseline.json"
  "non_kolme_wave_trend_test_loc_soft_budget_thresholds.json"
  "threshold_refreshed_on"
  "threshold_max_age_days"
  "check_non_kolme_wave_trend_test_loc_soft_budget.py"
  "check_non_kolme_wave_trend_test_loc_soft_budget.sh"
  "test_check_non_kolme_wave_trend_test_loc_soft_budget.sh"
  ".ci/non_kolme_wave_trend_test_loc_soft_budget_waiver.json"
  "test_ci_strategy_wave_range_marker_contract.sh"
  "non_kolme_wrapper_family_wave_range="
  "changes map to CI contract scope"
  "Wave-10 wrapper-family fixture and trend-checker changes map to CI contract scope:"
  "unknown/full fallback remains disabled for this path"
  "run_runtime_snapshot_contract_tests=true"
  "test_scope=runtime-contract"
  "run_localhost_signed_integration_contract_lane_tests"
  "sdk-live-localhost-integration"
  "KAMN_CI_TOOLS_FAST_MODE=true"
  "test_check_legacy_ingress_parser_drift.sh"
  "check_legacy_ingress_parser_drift.sh --source-root crates/kamn-node/src --baseline-file fixtures/ci/legacy_ingress_parser_baseline.json --output-json /tmp/legacy-ingress-parser-drift-report.json"
  "reason_codes=legacy_ingress_parser_marker_count_increased"
  "reason_codes=legacy_ingress_parser_marker_new_file"
  "reason_codes=legacy_ingress_parser_baseline_missing"
  "reason_codes=legacy_ingress_parser_baseline_invalid"
  "test_validate_service_api_observability_route_compatibility_live.sh"
  "test_check_service_api_observability_route_compatibility_live_policy.sh"
  "test_validate_service_api_observability_route_compatibility_live_contract_lane.sh"
  "KAMN_SERVICE_API_OBSERVABILITY_ROUTE_COMPATIBILITY_CONTRACT_MAX_SECONDS"
  "service_api_observability_route_compatibility_policy_matrix_row_status_mismatch:api_healthz_get"
  "run_live_transport_replay_tamper_fast_lane.sh"
  "check_live_transport_replay_tamper_policy.sh"
  "KAMN_SDK_REPLAY_TAMPER_CONTRACT_MAX_SECONDS=60"
  "run_live_transport_parity_contract_tests=true"
  "live_transport_parity_languages=rust,python,typescript"
  "run_kolme_version_compatibility_contract_tests=true"
  "test_scope=kolme-version-contract"
  "run_local_fork_sync_metadata_lane.sh --mode run"
  "run_local_fork_smoke_evidence_lane.sh --mode run"
  "run_local_kolme_api_probe_lane.sh --mode run --base-url http://127.0.0.1:3000 --fork-chain-version v0.15.2"
  "run_local_kolme_api_smoke_lane.sh --mode run"
  "run_local_kolme_live_api_conformance_harness.sh --mode run"
  "check_local_kolme_live_api_conformance_policy.py --report-file /tmp/kolme-local-live-api-conformance-summary.json"
  "run_local_kolme_live_api_conformance_contract_lane.sh --output-json /tmp/kolme-local-live-api-conformance-summary.json --policy-output-json /tmp/kolme-local-live-api-conformance-policy.json"
  "run_local_kolme_fork_bootstrap_readiness_lane.sh --mode run"
  "check_local_kolme_fork_bootstrap_readiness_policy.py --report-file /tmp/kolme-local-fork-bootstrap-readiness-summary.json"
  "run_local_kolme_fork_bootstrap_readiness_contract_lane.sh --output-json /tmp/kolme-local-fork-bootstrap-readiness-summary.json --policy-output-json /tmp/kolme-local-fork-bootstrap-readiness-policy.json"
  "run_local_kamn_live_runtime_integration_lane.sh --mode run"
  "--runtime-commit-live-policy-report /tmp/kolme-local-runtime-commit-live-policy.json"
  "check_local_kamn_live_runtime_integration_policy.py --report-file /tmp/kolme-local-kamn-live-runtime-integration-summary.json"
  "run_local_kamn_live_runtime_integration_contract_lane.sh --output-json /tmp/kolme-local-kamn-live-runtime-integration-summary.json --policy-output-json /tmp/kolme-local-kamn-live-runtime-integration-policy.json"
  "run_local_kolme_fork_process_lifecycle_lane.sh --mode run"
  "check_local_kolme_fork_process_lifecycle_policy.py --report-file /tmp/kolme-local-fork-process-lifecycle-summary.json"
  "run_local_kolme_fork_process_lifecycle_contract_lane.sh --output-json /tmp/kolme-local-fork-process-lifecycle-summary.json --policy-output-json /tmp/kolme-local-fork-process-lifecycle-policy.json"
  "run_local_runtime_commit_live_lane.sh --mode run"
  "check_local_runtime_commit_live_evidence_policy.py --report-file /tmp/kolme-local-runtime-commit-live-summary.json"
  "run_local_runtime_commit_live_finality_evidence_contract_lane.sh --output-json /tmp/kolme-local-runtime-commit-live-summary.json --policy-output-json /tmp/kolme-local-runtime-commit-live-policy.json"
  "submit_evidence_marker_present"
  "finality_evidence_marker_present"
  "run_local_native_api_parity_live_proof_lane.sh --mode run"
  "--request PUT --data '{\\\"message\\\":\\\"native-parity\\\",\\\"signature\\\":\\\"sig\\\",\\\"recovery_id\\\":1}' http://127.0.0.1:3000/broadcast"
  "test_run_local_runtime_commit_live_lane.sh"
  "test_run_local_native_api_parity_live_proof_contract_lane.sh"
  "test_generate_fork_compatibility_evidence.sh"
  "test_check_fork_compatibility_policy.sh"
  "test_run_runtime_commit_adapter_contract_lane.sh"
  "test_check_runtime_commit_decomposition_parity_matrix.sh"
  "test_kolme_tranche1_manifest_migration_contract.sh"
  "run_snapshot_drift_contract_lane.sh"
  "run_notifications_consumer_contract_lane.sh"
  "run_block_fallback_reconciliation_contract_lane.sh"
  "combined migrated wrapper shell LOC must remain"
  "test_kolme_runtime_nonce_manifest_migration_contract.sh"
  "test_kolme_version_matrix_manifest_migration_contract.sh"
  "test_kolme_profile_selftest_portability_manifest_migration_contract.sh"
  "test_kolme_runtime_triadic_bootstrap_e2e_manifest_migration_contract.sh"
  "test_kolme_bootstrap_conformance_runtime_process_manifest_migration_contract.sh"
  "test_kolme_manifest_migration_contract_dispatch_wrapper_matrix.sh"
  "test_run_kolme_manifest_migration_contract_dispatch.sh"
  "run_kolme_manifest_migration_contract_dispatch.sh"
  "kolme_manifest_migration_contract_groups.json"
  "kolme_wave10_wrapper_family_matrix.json"
  "kolme_wave10_wrapper_family_baseline.json"
  "kolme_wave10_wrapper_family_trend_thresholds.json"
  "kolme_wave11_wrapper_family_matrix.json"
  "kolme_wave11_wrapper_family_baseline.json"
  "kolme_wave11_wrapper_family_trend_thresholds.json"
  "generate_kolme_wrapper_inventory_baseline.sh --matrix-file fixtures/ci/kolme_wave10_wrapper_family_matrix.json --output-json /tmp/kolme-wave10-wrapper-family-baseline.json"
  "check_kolme_wrapper_inventory_baseline.sh --matrix-file fixtures/ci/kolme_wave10_wrapper_family_matrix.json --baseline-file fixtures/ci/kolme_wave10_wrapper_family_baseline.json --output-json /tmp/kolme-wave10-wrapper-family-delta.json"
  "generate_kolme_wrapper_inventory_baseline.sh --matrix-file fixtures/ci/kolme_wave11_wrapper_family_matrix.json --output-json /tmp/kolme-wave11-wrapper-family-baseline.json"
  "check_kolme_wrapper_inventory_baseline.sh --matrix-file fixtures/ci/kolme_wave11_wrapper_family_matrix.json --baseline-file fixtures/ci/kolme_wave11_wrapper_family_baseline.json --output-json /tmp/kolme-wave11-wrapper-family-delta.json"
  "check_kolme_wave10_wrapper_family_budget_trend.sh --matrix-file fixtures/ci/kolme_wave10_wrapper_family_matrix.json --baseline-file fixtures/ci/kolme_wave10_wrapper_family_baseline.json --output-json /tmp/kolme-wave10-wrapper-family-trend-report.json"
  "check_kolme_wave11_wrapper_family_budget_trend.sh --matrix-file fixtures/ci/kolme_wave11_wrapper_family_matrix.json --baseline-file fixtures/ci/kolme_wave11_wrapper_family_baseline.json --output-json /tmp/kolme-wave11-wrapper-family-trend-report.json"
  "test_kolme_wave10_wrapper_family_baseline_contract.sh"
  "test_check_kolme_wave10_wrapper_family_budget_trend.sh"
  "test_kolme_wave11_wrapper_family_baseline_contract.sh"
  "test_check_kolme_wave11_wrapper_family_budget_trend.sh"
  "test_check_non_kolme_wave_trend_test_loc_soft_budget.sh"
  "check_non_kolme_wave_trend_test_loc_soft_budget.sh --output-json /tmp/non-kolme-wave-trend-test-loc-soft-budget-report.json"
  "check_non_kolme_wave_trend_test_loc_soft_budget.sh --waiver-file .ci/non_kolme_wave_trend_test_loc_soft_budget_waiver.json --output-json /tmp/non-kolme-wave-trend-test-loc-soft-budget-report.json"
  "reason_codes=script_count_delta_threshold_exceeded"
  "reason_codes=total_shell_loc_delta_threshold_exceeded"
  "reason_codes=threshold_json_invalid"
  "reason_codes=threshold_refresh_metadata_invalid"
  "reason_codes=threshold_refreshed_on_invalid"
  "reason_codes=threshold_file_stale"
  "reason_codes=missing_baseline_scripts"
  "reason_codes=unexpected_current_scripts"
  "reason_codes=waiver_scope_mismatch"
  "reason_codes=waiver_expired"
  "waiver_status=none|applied"
  "waived_reason_codes=none|..."
  "remediation=..."
  "test_check_kamn_node_main_rs_extraction_threshold.sh"
  "fixtures/ci/kamn_node_main_rs_extraction_thresholds.json"
  "check_kamn_node_main_rs_extraction_threshold.sh --output-json /tmp/kamn-node-main-rs-extraction-threshold-report.json"
  "check_kamn_node_main_rs_extraction_threshold.sh --exception-file .ci/kamn_node_main_rs_extraction_threshold_exception.json --output-json /tmp/kamn-node-main-rs-extraction-threshold-report.json"
  "policy_decision=GO|WARN|NO-GO"
  "exception_status=not-required|not-provided|applied|invalid|cap-exceeded"
  "reason_codes=main_rs_line_count_warn_threshold_exceeded"
  "reason_codes=main_rs_line_count_fail_threshold_exceeded"
  "reason_codes=main_rs_threshold_exception_applied"
  "reason_codes=main_rs_threshold_exception_expired"
  "reason_codes=main_rs_threshold_exception_cap_exceeded"
  "reason_codes=threshold_order_invalid"
  "test_check_kamn_node_runtime_orchestration_rs_extraction_threshold.sh"
  "fixtures/ci/kamn_node_runtime_orchestration_rs_extraction_thresholds.json"
  "check_kamn_node_runtime_orchestration_rs_extraction_threshold.sh --output-json /tmp/kamn-node-runtime-orchestration-rs-extraction-threshold-report.json"
  "check_kamn_node_runtime_orchestration_rs_extraction_threshold.sh --exception-file .ci/kamn_node_runtime_orchestration_rs_extraction_threshold_exception.json --output-json /tmp/kamn-node-runtime-orchestration-rs-extraction-threshold-report.json"
  "cargo test -p kamn-node --test main_module_extraction_contract"
  "reason_codes=runtime_orchestration_rs_line_count_warn_threshold_exceeded"
  "reason_codes=runtime_orchestration_rs_line_count_fail_threshold_exceeded"
  "reason_codes=runtime_orchestration_rs_threshold_exception_applied"
  "reason_codes=runtime_orchestration_rs_threshold_exception_expired"
  "reason_codes=runtime_orchestration_rs_threshold_exception_cap_exceeded"
  "Non-Kolme governance dispatcher wrapper-matrix guard stays on PR fast gate:"
  "test_non_kolme_contract_lane_dispatch_wrapper_matrix.sh"
  "Non-Kolme compliance dispatcher wrapper-matrix guard stays on PR fast gate:"
  "test_non_kolme_compliance_contract_lane_dispatch_wrapper_matrix.sh"
  "Non-Kolme manifest-backed dispatcher wrapper-matrix guard stays on PR fast gate:"
  "test_non_kolme_manifest_backed_contract_lane_dispatch_wrapper_matrix.sh"
  "Non-Kolme bridge dispatcher wrapper-matrix guard stays on PR fast gate:"
  "test_non_kolme_bridge_contract_lane_dispatch_wrapper_matrix.sh"
  "Non-Kolme sdk dispatcher wrapper-matrix guard stays on PR fast gate:"
  "test_non_kolme_sdk_contract_lane_dispatch_wrapper_matrix.sh"
  "Non-Kolme lightweight dispatcher wrapper-matrix guard stays on PR fast gate:"
  "test_non_kolme_lightweight_contract_lane_dispatch_wrapper_matrix.sh"
  "run_non_kolme_contract_lane_dispatch.sh"
  "run_governance_simulation_contract_lane.sh"
  "Regression: #2649"
  "Regression: #2652"
  "Regression: #2655"
  "Regression: #2658"
  "Regression: #2703"
  "Regression: #2705"
  "Regression: #2711"
  "Regression: #2714"
  "Regression: #2717"
  "Regression: #2720"
  "Regression: #2723"
  "Regression: #2726"
  "Regression: #2729"
  "Regression: #2732"
  "Regression: #2735"
  "Regression: #2738"
  "Regression: #2741"
  "Regression: #2769"
  "Regression: #2777"
  "lane_source_entry_drift"
  "min_wrapper_count_reduction"
  "min_total_shell_loc_reduction"
  "wrapper_count_reduction_target_unmet"
  "total_shell_loc_reduction_target_unmet"
  "run_local_kamn_live_runtime_real_node_profile_contract_lane.sh"
  "run_local_kolme_live_deployment_preflight_contract_lane.sh"
  "Regression: #2281"
  "run_runtime_commit_adapter_contract_lane.sh"
  "run_runtime_commit_replay_contract_lane.sh"
  "run_nonce_broadcast_parity_contract_lane.sh"
  "run_version_compatibility_contract_lane.sh"
  "run_local_kolme_fork_rust_test_matrix_contract_lane.sh"
  "run_local_heavy_validation_matrix_contract_lane.sh"
  "run_runtime_commit_contract_lane.sh"
  "check_runtime_commit_decomposition_parity_matrix.py check --matrix-file fixtures/kolme_compatibility/runtime_commit_decomposition_parity_matrix.json --output-json /tmp/runtime-commit-decomposition-parity-policy.json"
  "runtime_commit_decomposition_parity_matrix.json"
  "run_triadic_devnet_smoke_contract_lane.sh"
  "run_local_bootstrap_health_checks_contract_lane.sh"
  "run_local_e2e_integration_contract_lane.sh"
  "runtime+nonce manifest migration guard stays on PR fast gate:"
  "version+matrix manifest migration guard stays on PR fast gate:"
  "profile+self-test+portability manifest migration guard stays on PR fast gate:"
  "runtime+triadic+bootstrap+e2e manifest migration guard stays on PR fast gate:"
  "bootstrap+conformance+runtime+process manifest migration guard stays on PR fast gate:"
  "parity+demo+real-process manifest migration guard stays on PR fast gate:"
  "test_kolme_parity_demo_real_process_manifest_migration_contract.sh"
  "test_run_local_kolme_fork_rust_test_matrix_lane.sh"
  "test_check_local_kolme_fork_rust_test_matrix_policy.sh"
  "test_run_local_kolme_fork_rust_test_matrix_contract_lane.sh"
  "test_run_signature_parity_matrix.sh"
  "test_check_signature_parity_policy.sh"
  "test_run_signature_parity_contract_lane.sh"
  "Regression: #2348"
  "run_local_kolme_fork_rust_test_matrix_contract_lane.sh --output-json /tmp/kolme-local-fork-rust-test-matrix-summary.json --policy-output-json /tmp/kolme-local-fork-rust-test-matrix-policy.json"
  "test_run_local_kolme_live_api_conformance_contract_lane.sh"
  "test_run_local_kolme_fork_bootstrap_readiness_contract_lane.sh"
  "test_run_local_kamn_live_runtime_integration_contract_lane.sh"
  "test_run_local_kolme_fork_process_lifecycle_contract_lane.sh"
  "test_run_local_kolme_fork_profile_preflight_contract_lane.sh"
  "test_run_local_kolme_fork_self_test_contract_lane.sh"
  "test_run_local_kolme_fork_portability_preflight_contract_lane.sh"
  "test_run_fast_gate_native_api_parity_contract_lane.sh"
  "run_fast_gate_native_api_parity_contract_lane.sh --output-json /tmp/kolme-fast-gate-native-api-parity-summary.json"
  "check_fast_gate_native_api_parity_policy.py --report-file /tmp/kolme-fast-gate-native-api-parity-summary.json"
  "KAMN_KOLME_FAST_GATE_NATIVE_PARITY_MAX_SECONDS=120"
  "test_run_nonce_broadcast_parity_contract_lane.sh"
  "KAMN_KOLME_NONCE_BROADCAST_PARITY_MAX_SECONDS=60"
  "run_local_bootstrap_health_checks.sh"
  "check_local_bootstrap_health_policy.py --report-file /tmp/kolme-local-bootstrap-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code dry_run_no_commands_executed --output-json /tmp/kolme-local-bootstrap-policy.json"
  "run_local_bootstrap_health_checks_contract_lane.sh --output-json /tmp/kolme-local-bootstrap-summary.json --policy-output-json /tmp/kolme-local-bootstrap-policy.json"
  "test_check_local_bootstrap_health_policy.sh"
  "test_run_local_bootstrap_health_checks_contract_lane.sh"
  "run_local_e2e_integration_lane.sh"
  "check_local_e2e_integration_policy.py --report-file /tmp/kolme-local-e2e-integration-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code dry_run_no_commands_executed --output-json /tmp/kolme-local-e2e-integration-policy.json"
  "run_local_e2e_integration_contract_lane.sh --output-json /tmp/kolme-local-e2e-integration-summary.json --policy-output-json /tmp/kolme-local-e2e-integration-policy.json"
  "run_local_heavy_validation_matrix.sh --mode dry-run --output-json /tmp/kolme-local-heavy-validation-summary.json"
  "check_local_heavy_validation_matrix_policy.py --report-file /tmp/kolme-local-heavy-validation-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code dry_run_no_commands_executed --output-json /tmp/kolme-local-heavy-validation-policy.json"
  "run_local_heavy_validation_matrix_contract_lane.sh --output-json /tmp/kolme-local-heavy-validation-summary.json --policy-output-json /tmp/kolme-local-heavy-validation-policy.json"
  "scenario_matrix_schema_version=kamn.kolme.local-heavy-validation-scenario-matrix.v1"
  "scenario_runtime_mode=dry-run|run"
  "scenario_runtime_profiles=real-node"
  "scenario_count=9"
  "scenario_ids=bootstrap_health,version_compatibility_replay,fork_rust_matrix,live_api_conformance,signature_parity,runtime_commit_finality,native_api_parity,real_node_runtime_integration,real_node_runtime_policy"
  "scenario_matrix_schema_version_mismatch"
  "scenario_ids_mismatch"
  "scenario_runtime_mode_mismatch"
  "scenario_command_missing:<scenario_id>"
  "scenario_artifact_missing:<scenario_id>"
  "KAMN_KOLME_LOCAL_HEAVY=1"
  "kolme_local_heavy_lane_mode=local-only|manual-opt-in|not-applicable"
  "check_workflow_kolme_heavy_exclusion_policy.py --workflow-file .github/workflows/ci-fast-gate.yml --selector-file scripts/ci/select_targets.sh"
  "selector_local_heavy_commands_missing"
  "selector_output_run_flag_missing"
  "selector_output_opt_in_flag_missing"
  "local-only heavy Kolme run-mode commands remain excluded from ci-fast-gate."
  "local-only fork sync/smoke run-mode commands remain excluded from ci-fast-gate."
  "local Kolme API probe/smoke run-mode commands remain excluded from ci-fast-gate."
  "local live API conformance harness run-mode commands remain excluded from ci-fast-gate."
  "local fork bootstrap/readiness run-mode commands remain excluded from ci-fast-gate."
  "local KAMN live runtime integration run-mode commands remain excluded from ci-fast-gate."
  "local invariant/fuzz/concurrency run-mode commands remain excluded from ci-fast-gate."
  "run_invariant_fuzz_concurrency_contract_lane.sh --output-json /tmp/invariant-fuzz-concurrency-contract-report.json"
  "check_invariant_fuzz_concurrency_policy.sh --report-file /tmp/invariant-fuzz-concurrency-contract-report.json"
  "run_concurrency_state_mutation_contract_lane.sh --output-json /tmp/concurrency-state-mutation-contract-report.json"
  "check_local_kamn_live_runtime_real_node_profile_policy.py --report-file /tmp/kolme-local-kamn-live-runtime-integration-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code dry_run_no_commands_executed --require-non-synthetic-run-evidence --output-json /tmp/kolme-local-kamn-live-runtime-real-node-policy.json"
  "signer rotation/failover drill lane remains local-heavy and excluded from ci-fast-gate."
  "runtime_commit_command_profile=real-node-non-synthetic-v1"
  "runtime_commit_policy_command_profile=real-node-non-synthetic-v1"
  "runtime_commit_command_profile_version=v1"
  "runtime_commit_command_profile_mismatch"
  "runtime_commit_non_synthetic_submit_probe_missing"
  "integration_kolme_fork_live_node_submit_reaches_endpoint"
  "strict real-node runtime evidence marker path remains local-only and excluded from ci-fast-gate."
  "selector routing for native parity command/policy/manifest changes:"
  "native parity local-heavy budget markers are enforced in matrix policy:"
  "native_runtime_commit_budget_marker_missing"
  "native_api_parity_budget_marker_missing"
  "native_real_node_budget_marker_missing"
  "native_real_node_policy_marker_missing"
  "deployment preflight signer/runtime checks remain fast and ci-fast-gate eligible."
  "run_local_kolme_live_deployment_preflight_lane.sh --mode dry-run --output-json /tmp/kolme-local-live-deployment-preflight-summary.json"
  "custody-attestation=ops-primary:epoch-1"
  "run_local_kolme_live_deployment_preflight_lane.sh --mode run --runtime-mode kolme-live --signer-profile ops-primary --required-approvals 2 --received-approvals 2 --custody-evidence-file /tmp/kolme-live-signer-custody.json"
  "check_local_kolme_live_deployment_preflight_policy.py --report-file /tmp/kolme-local-live-deployment-preflight-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code dry_run_no_commands_executed --output-json /tmp/kolme-local-live-deployment-preflight-policy.json"
  "run_local_kolme_live_deployment_preflight_contract_lane.sh --output-json /tmp/kolme-local-live-deployment-preflight-summary.json --policy-output-json /tmp/kolme-local-live-deployment-preflight-policy.json"
  "required_approvals=2"
  "received_approvals=2"
  "contracts.ci_fast_gate_scope=ci-fast-gate"
  "contracts.approval_quorum_required=2"
  "contracts.custody_evidence_required=true"
  "runtime_mode_mismatch"
  "checkpoint_failed_signer_secret_contract"
  "checkpoint_failed_signer_quorum_contract"
  "checkpoint_failed_custody_evidence_contract"
  "signer_quorum_shortfall"
  "custody_evidence_missing"
  "custody_evidence_sha256_invalid"
  "Regression: #2226"
  "local fork process lifecycle integration run-mode commands remain excluded from ci-fast-gate."
  "local fork profile preflight run-mode commands remain excluded from ci-fast-gate."
  "check_local_kolme_fork_profile_preflight_policy.py --report-file /tmp/kolme-local-fork-profile-preflight-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code profile_preflight_passed --output-json /tmp/kolme-local-fork-profile-preflight-policy.json"
  "run_local_kolme_fork_profile_preflight_contract_lane.sh --output-json /tmp/kolme-local-fork-profile-preflight-summary.json --policy-output-json /tmp/kolme-local-fork-profile-preflight-policy.json"
  "local fork self-test run-mode commands remain excluded from ci-fast-gate."
  "check_local_kolme_fork_self_test_policy.py --report-file /tmp/kolme-local-fork-self-test-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code fork_self_test_passed --output-json /tmp/kolme-local-fork-self-test-policy.json"
  "run_local_kolme_fork_self_test_contract_lane.sh --output-json /tmp/kolme-local-fork-self-test-summary.json --policy-output-json /tmp/kolme-local-fork-self-test-policy.json"
  "local fork portability preflight run-mode commands remain excluded from ci-fast-gate."
  "check_local_kolme_fork_portability_preflight_policy.py --report-file /tmp/kolme-local-fork-portability-preflight-summary.json --expected-final-decision GO --ci-fast-gate PASS --require-reason-code portability_preflight_passed --output-json /tmp/kolme-local-fork-portability-preflight-policy.json"
  "run_local_kolme_fork_portability_preflight_contract_lane.sh --output-json /tmp/kolme-local-fork-portability-preflight-summary.json --policy-output-json /tmp/kolme-local-fork-portability-preflight-policy.json"
  "local runtime-commit live run-mode commands remain excluded from ci-fast-gate."
  "local native API parity live-proof run-mode commands remain excluded from ci-fast-gate."
  "validate_local_retry_diagnostics_live.sh --mode dry-run --output-json /tmp/runtime-local-retry-diagnostics-summary.json"
  "KAMN_LOCAL_RETRY_DIAGNOSTICS_OPT_IN=1 bash scripts/runtime/validate_local_retry_diagnostics_live.sh --mode run --output-json /tmp/runtime-local-retry-diagnostics-summary.json"
  "check_local_retry_diagnostics_live_policy.sh --report-file /tmp/runtime-local-retry-diagnostics-summary.json --expected-final-decision GO --ci-fast-gate PASS --output-json /tmp/runtime-local-retry-diagnostics-policy.json"
  "validate_local_retry_diagnostics_live_contract_lane.sh --output-json /tmp/runtime-local-retry-diagnostics-contract-lane-report.json --policy-output-json /tmp/runtime-local-retry-diagnostics-policy.json"
  "test_validate_local_retry_diagnostics_live.sh"
  "test_check_local_retry_diagnostics_live_policy.sh"
  "test_validate_local_retry_diagnostics_live_contract_lane.sh"
  "local retry/diagnostics run-mode commands remain excluded from ci-fast-gate and ci-tools fast mode."
  "local_retry_diagnostics_policy_marker_missing:correlation_diagnostics_status"
  "validate_local_signal_secret_hygiene_live.sh --mode dry-run --output-json /tmp/runtime-local-signal-secret-hygiene-summary.json"
  "KAMN_LOCAL_SIGNAL_SECRET_HYGIENE_OPT_IN=1 bash scripts/runtime/validate_local_signal_secret_hygiene_live.sh --mode run --output-json /tmp/runtime-local-signal-secret-hygiene-summary.json"
  "check_local_signal_secret_hygiene_live_policy.sh --report-file /tmp/runtime-local-signal-secret-hygiene-summary.json --expected-final-decision GO --ci-fast-gate PASS --output-json /tmp/runtime-local-signal-secret-hygiene-policy.json"
  "validate_local_signal_secret_hygiene_live_contract_lane.sh --output-json /tmp/runtime-local-signal-secret-hygiene-contract-lane-report.json --policy-output-json /tmp/runtime-local-signal-secret-hygiene-policy.json"
  "test_validate_local_signal_secret_hygiene_live.sh"
  "test_check_local_signal_secret_hygiene_live_policy.sh"
  "test_validate_local_signal_secret_hygiene_live_contract_lane.sh"
  "local signal/secret hygiene run-mode commands remain excluded from ci-fast-gate and ci-tools fast mode."
  "run_daemon_os_signal_reproducer.sh --attempts 3 --max-seconds 180 --artifact-dir /tmp/daemon-os-signal-reproducer-artifacts --output-json /tmp/daemon-os-signal-reproducer-report.json"
  "test_run_daemon_os_signal_reproducer.sh"
  "kamn.ci.daemon-os-signal-reproducer-report.v1"
  "test_name, attempt_index, run_index, status, exit_code, log_file, stdout_excerpt, failure_markers"
  "run_daemon_os_signal_stress_matrix.sh --iterations 10 --attempts-per-iteration 1 --max-seconds 600 --reproducer-max-seconds 180 --failure-threshold 0 --artifact-dir /tmp/daemon-os-signal-stress-matrix-artifacts --output-json /tmp/daemon-os-signal-stress-matrix-report.json"
  "test_run_daemon_os_signal_stress_matrix.sh"
  "kamn.ci.daemon-os-signal-stress-matrix-report.v1"
  "iterations, attempts_per_iteration, failure_threshold, pass_iterations, fail_iterations, quarantine_status, anti_flake_chain_artifacts, iteration_results"
  "iteration_index, status, exit_code, reproducer_reason_code, reproducer_report_file"
  "stable_success_with_quarantine_followup"
  "matrix_failures_within_threshold"
  "matrix_failure_threshold_exceeded"
  "quarantine_registry_missing"
  "quarantine_reference_present_without_followup"
  "targeted daemon OS-signal tests must be absent from .ci/flaky-tests.txt"
  "check_anti_flake_policy.sh --registry-file .ci/flaky-tests.txt --expected-final-decision GO --max-active-entries 0 --fast-workflow-file .github/workflows/ci-fast-gate.yml --deep-workflow-file .github/workflows/ci-deep-validate.yml --output-json /tmp/anti-flake-policy-report.json"
  "kamn.ci.anti-flake-policy-report.v1"
  "anti_flake_policy_reason_taxonomy_version=kamn.ci.anti-flake-policy-reason-taxonomy.v1"
  "anti_flake_policy_status=pass|fail"
  "anti_flake_policy_final_decision=GO|NO-GO"
  "anti_flake_policy_reason_codes_csv=none|<csv>"
  "anti_flake_policy_reason_codes_value=none|<csv>"
  "anti_flake_policy_reason_class=stable|budgeted|violation"
  "no_active_flaky_entries"
  "active_flaky_entries_within_budget"
  "active_flaky_entries_exceed_max"
  "registry_validation_failed"
  "registry_file_missing"
  "expected_final_decision_mismatch"
  "rerun_policy_fast_workflow_missing"
  "rerun_policy_deep_workflow_missing"
  "rerun_policy_bounded_retry_missing"
  "rerun_policy_invariant_non_retry_missing"
  "rerun_policy_excessive_retry_detected"
  "ci-anti-flake-policy-report.json"
  "fallback_signer_secret_present_violation"
  "native parity fast/local command matrix remains synchronized across"
  "run_dashboard_contract_tests=true"
  "test_scope=frontend-contract"
  "run_frontend_dashboard_tests=true"
  "test_scope=frontend"
  "run_deploy_preflight_tests=true"
  "test_scope=deploy"
  "run_settlement_reconciliation_contract_tests=true"
  "test_scope=escrow-contract"
  "run_bridge_replay_harness=true"
  "test_scope=bridge"
  "run_localhost_signed_integration_contract_lane.sh"
  "run_backend_session_auth_freshness_contract_lane.sh"
  "run_dashboard_stale_error_budget_contract_lane.sh"
  "run_dashboard_shell_determinism_matrix_contract_lane.sh"
  "run_deployment_slo_rollback_contract_lane.sh"
  "run_settlement_reconciliation_contract_lane.sh"
  "run_bridge_adapter_conformance_contract_lane.sh"
  "run_post_cutover_slo_contract_lane.sh"
  "run_classification_redaction_contract_lane.sh"
  "run_quorum_attestation_replay_contract_lane.sh"
  "test_run_kamn_core_rustdoc_artifact_contract_lane.sh"
  "test_check_kamn_core_rustdoc_artifact_policy.sh"
  "check_kamn_core_live_https_dependency_posture.sh --output-json /tmp/kamn-core-live-https-dependency-posture-report.json"
  "test_check_kamn_core_live_https_dependency_posture.sh"
  "Ignored-test inventory drift policy (fail-closed):"
  "fixtures/ci/ignored_test_inventory_baseline.json"
  "fixtures/ci/ignored_test_inventory_metadata.json"
  "fixtures/ci/ignored_test_promotion_criteria.json"
  "check_ignored_test_inventory_drift.sh --baseline-file fixtures/ci/ignored_test_inventory_baseline.json --metadata-file fixtures/ci/ignored_test_inventory_metadata.json --promotion-criteria-file fixtures/ci/ignored_test_promotion_criteria.json --output-json /tmp/ignored-test-inventory-drift-report.json"
  "test_check_ignored_test_inventory_drift.sh"
  "test_check_ignored_test_inventory_metadata_policy.sh"
  "reason_codes=ignored_test_metadata_missing"
  "reason_codes=high_priority_tracking_issue_missing"
  "reason_codes=ignored_test_promotion_criteria_missing"
  "Regression: #2841"
  "Regression: #2842"
  "Regression: #2843"
  "test_missing_docs_velocity_guard_contract.sh"
  "missing_docs_velocity_guard.py check --report-file /tmp/kamn-core-missing-docs-throughput-report.json"
  ".ci/kamn-core-missing-docs-velocity-thresholds.json"
  "docs/planning/issues/missing-docs-velocity-cadence.md"
  "test_missing_docs_graduation_batch_report_contract.sh"
  "docs/planning/issues/missing-docs-first-batch-graduation-report.md"
  "scripts/ci/select_targets.sh"
  "Regression: #900"
  "Regression: #939"
  "Regression: #906"
  "Regression: #913"
  "Regression: #914"
  "Regression: #911"
  "Regression: #942"
  "Regression: #943"
  "Regression: #941"
  "Regression: #944"
  "Regression: #907"
  "Regression: #1386"
  "Regression: #1419"
  "Regression: #1431"
  "Regression: #1682"
  "Regression: #1687"
  "Regression: #1697"
  "Regression: #1702"
  "Regression: #1707"
  "Regression: #1692"
  "Regression: #1441"
  "Regression: #1451"
  "Regression: #1467"
  "Regression: #1468"
  "Regression: #1482"
  "Regression: #1483"
  "Regression: #1488"
  "Regression: #1489"
  "Regression: #1494"
  "Regression: #1462"
  "Regression: #1466"
  "Regression: #1497"
  "Regression: #2126"
  "Regression: #2127"
  "Regression: #2124"
  "Regression: #2093"
  "Regression: #2095"
  "Regression: #2099"
  "Regression: #2101"
  "Regression: #1561"
  "Regression: #1565"
  "Regression: #1569"
  "Regression: #1722"
  "Regression: #1763"
  "Regression: #1765"
  "Regression: #1767"
  "Regression: #1769"
  "Regression: #1771"
  "Regression: #1773"
  "Regression: #1833"
)

for ((wave = wave_start; wave <= wave_end; wave++)); do
  required_snippets+=(
    "non_kolme_wave${wave}_wrapper_family_matrix.json"
    "non_kolme_wave${wave}_wrapper_family_baseline.json"
    "non_kolme_wave${wave}_wrapper_family_trend_thresholds.json"
    "check_non_kolme_wave${wave}_wrapper_family_budget_trend.sh"
    "test_non_kolme_wave${wave}_wrapper_family_baseline_contract.sh"
    "test_check_non_kolme_wave${wave}_wrapper_family_budget_trend.sh"
    "generate_kolme_wrapper_inventory_baseline.sh --matrix-file fixtures/ci/non_kolme_wave${wave}_wrapper_family_matrix.json --output-json /tmp/non-kolme-wave${wave}-wrapper-family-baseline.json"
    "check_kolme_wrapper_inventory_baseline.sh --matrix-file fixtures/ci/non_kolme_wave${wave}_wrapper_family_matrix.json --baseline-file fixtures/ci/non_kolme_wave${wave}_wrapper_family_baseline.json --output-json /tmp/non-kolme-wave${wave}-wrapper-family-delta.json"
    "check_non_kolme_wave${wave}_wrapper_family_budget_trend.sh --matrix-file fixtures/ci/non_kolme_wave${wave}_wrapper_family_matrix.json --baseline-file fixtures/ci/non_kolme_wave${wave}_wrapper_family_baseline.json --output-json /tmp/non-kolme-wave${wave}-wrapper-family-trend-report.json"
  )
done

for lightweight_wave in {10..18}; do
  required_snippets+=(
    "Non-Kolme wave-${lightweight_wave} lightweight dispatcher wrapper-matrix guard stays on PR fast gate:"
    "test_non_kolme_wave${lightweight_wave}_lightweight_contract_lane_dispatch_wrapper_matrix.sh"
  )
done

for snippet in "${required_snippets[@]}"; do
  if ! grep -Fq -- "$snippet" "$STRATEGY_DOC"; then
    echo "CI strategy contract failed: missing snippet '$snippet'." >&2
    exit 1
  fi
done

echo "CI strategy contract tests passed."
