//! MVP evaluator demo report generation and verification.

mod agent_harness;
mod agent_harness_actor_receipts;
mod agent_harness_actor_rehearsal;
mod agent_harness_json;
mod agent_harness_observation_receipts;
mod agent_harness_three_agent;
mod artifact_digest;
mod authoritative_rpc_verify;
mod command_config;
mod devnet_settlement;
mod devnet_settlement_build;
mod devnet_settlement_grant_bootstrap;
mod devnet_settlement_json;
mod devnet_settlement_live;
mod devnet_settlement_node;
mod devnet_settlement_service;
mod devnet_settlement_solana;
mod devnet_settlement_state;
mod independent_explorer_verify;
mod independent_settlement_verify;
mod independent_verifier;
mod independent_verifier_errors;
mod live_task_binding;
mod live_task_binding_verify;
mod live_task_funding_verify;
mod live_task_source_format;
mod live_task_sources;
mod local_artifact_paths;
mod local_artifact_verify;
mod local_artifacts;
mod localhost_signed;
mod pi_transaction_actor_model;
mod pi_transaction_actor_verify;
mod pi_transaction_public_result;
mod report;
mod report_artifacts;
mod report_devnet;
mod report_markdown;
mod report_writer;
mod runner;
mod runner_settlement;
mod runtime_actor_bundle;
mod runtime_receipt_chain;
mod runtime_receipt_chain_facts;
mod runtime_receipt_chain_precheck;
mod service_api_proof;
mod settlement_evidence_artifact;
mod settlement_log_verify;
mod three_agent_claim;
mod three_agent_receipt_spec;
mod three_agent_receipt_verify;
mod three_agent_receipt_verify_support;
mod three_agent_receipt_write;
mod three_agent_receipts;
mod three_agent_runtime_chain;
mod three_agent_transcript;
mod three_agent_transcript_build;
mod three_agent_verify;
mod three_agent_view_artifacts;
mod three_agent_view_verify;
mod three_agent_views;
mod verify;
mod verify_claims;
mod verify_support;

pub use command_config::{LiveTaskEvidencePaths, MvpDemoCommandConfig, VerifyMvpDemoCommandConfig};
pub(crate) use devnet_settlement::DevnetSettlementEvidence;
pub use pi_transaction_actor_verify::verify_pi_transaction_actor_paths;
pub use report::{
    CLAIM_LABEL_DEVNET_BACKED, CLAIM_LABEL_DRY_RUN, CLAIM_LABEL_LOCAL_ONLY,
    CLAIM_LABEL_PLACEHOLDER, CLAIM_LABEL_REAL, CLAIM_LABEL_ROADMAP, MVP_DEMO_REPORT_SCHEMA_VERSION,
};
pub(crate) use runner::execute_mvp_demo_contract_with_settlement;
pub use runner::{execute_mvp_demo_contract, execute_verify_mvp_demo_contract};
pub use runtime_receipt_chain::build_runtime_receipt_chain_from_actor_paths;
pub use verify::verify_mvp_demo_report_json;

pub(crate) const DEFAULT_MVP_DEMO_OUTPUT_ROOT: &str = ".kamn/demo";
