use super::support::assert_doc_contains_all;

const WRAPPER_FAMILY_WAVE_MARKERS: &[&str] = &[
    "non_kolme_wave5_wrapper_family_matrix.json",
    "non_kolme_wave5_wrapper_family_baseline.json",
    "non_kolme_wave5_wrapper_family_trend_thresholds.json",
    "test_non_kolme_wave5_wrapper_family_baseline_contract.sh",
    "test_check_non_kolme_wave5_wrapper_family_budget_trend.sh",
    "check_non_kolme_wave5_wrapper_family_budget_trend.sh",
    "non_kolme_wave6_wrapper_family_matrix.json",
    "non_kolme_wave6_wrapper_family_baseline.json",
    "non_kolme_wave6_wrapper_family_trend_thresholds.json",
    "test_non_kolme_wave6_wrapper_family_baseline_contract.sh",
    "test_check_non_kolme_wave6_wrapper_family_budget_trend.sh",
    "check_non_kolme_wave6_wrapper_family_budget_trend.sh",
    "non_kolme_wave7_wrapper_family_matrix.json",
    "non_kolme_wave7_wrapper_family_baseline.json",
    "non_kolme_wave7_wrapper_family_trend_thresholds.json",
    "test_non_kolme_wave7_wrapper_family_baseline_contract.sh",
    "test_check_non_kolme_wave7_wrapper_family_budget_trend.sh",
    "check_non_kolme_wave7_wrapper_family_budget_trend.sh",
    "non_kolme_wave8_wrapper_family_matrix.json",
    "non_kolme_wave8_wrapper_family_baseline.json",
    "non_kolme_wave8_wrapper_family_trend_thresholds.json",
    "test_non_kolme_wave8_wrapper_family_baseline_contract.sh",
    "test_check_non_kolme_wave8_wrapper_family_budget_trend.sh",
    "check_non_kolme_wave8_wrapper_family_budget_trend.sh",
    "non_kolme_wave9_wrapper_family_matrix.json",
    "non_kolme_wave9_wrapper_family_baseline.json",
    "non_kolme_wave9_wrapper_family_trend_thresholds.json",
    "test_non_kolme_wave9_wrapper_family_baseline_contract.sh",
    "test_check_non_kolme_wave9_wrapper_family_budget_trend.sh",
    "check_non_kolme_wave9_wrapper_family_budget_trend.sh",
    "non_kolme_wave10_wrapper_family_matrix.json",
    "non_kolme_wave10_wrapper_family_baseline.json",
    "non_kolme_wave10_wrapper_family_trend_thresholds.json",
    "test_non_kolme_wave10_wrapper_family_baseline_contract.sh",
    "test_check_non_kolme_wave10_wrapper_family_budget_trend.sh",
    "check_non_kolme_wave10_wrapper_family_budget_trend.sh",
    "kolme_wave10_wrapper_family_matrix.json",
    "kolme_wave10_wrapper_family_baseline.json",
    "kolme_wave10_wrapper_family_trend_thresholds.json",
    "test_kolme_wave10_wrapper_family_baseline_contract.sh",
    "test_check_kolme_wave10_wrapper_family_budget_trend.sh",
    "check_kolme_wave10_wrapper_family_budget_trend.sh",
    "kolme_wave11_wrapper_family_matrix.json",
    "kolme_wave11_wrapper_family_baseline.json",
    "kolme_wave11_wrapper_family_trend_thresholds.json",
    "test_kolme_wave11_wrapper_family_baseline_contract.sh",
    "test_check_kolme_wave11_wrapper_family_budget_trend.sh",
    "check_kolme_wave11_wrapper_family_budget_trend.sh",
    "non_kolme_wave11_wrapper_family_matrix.json",
    "non_kolme_wave11_wrapper_family_baseline.json",
    "non_kolme_wave11_wrapper_family_trend_thresholds.json",
    "test_non_kolme_wave11_wrapper_family_baseline_contract.sh",
    "test_check_non_kolme_wave11_wrapper_family_budget_trend.sh",
    "check_non_kolme_wave11_wrapper_family_budget_trend.sh",
    "non_kolme_wave12_wrapper_family_matrix.json",
    "non_kolme_wave12_wrapper_family_baseline.json",
    "non_kolme_wave12_wrapper_family_trend_thresholds.json",
    "test_non_kolme_wave12_wrapper_family_baseline_contract.sh",
    "test_check_non_kolme_wave12_wrapper_family_budget_trend.sh",
    "check_non_kolme_wave12_wrapper_family_budget_trend.sh",
    "non_kolme_wave13_wrapper_family_matrix.json",
    "non_kolme_wave13_wrapper_family_baseline.json",
    "non_kolme_wave13_wrapper_family_trend_thresholds.json",
    "test_non_kolme_wave13_wrapper_family_baseline_contract.sh",
    "test_check_non_kolme_wave13_wrapper_family_budget_trend.sh",
    "check_non_kolme_wave13_wrapper_family_budget_trend.sh",
];

const WRAPPER_FAMILY_TAIL_MARKERS: &[&str] = &[
    "non_kolme_wave14_wrapper_family_matrix.json",
    "non_kolme_wave14_wrapper_family_baseline.json",
    "non_kolme_wave14_wrapper_family_trend_thresholds.json",
    "test_non_kolme_wave14_wrapper_family_baseline_contract.sh",
    "test_check_non_kolme_wave14_wrapper_family_budget_trend.sh",
    "check_non_kolme_wave14_wrapper_family_budget_trend.sh",
    "non_kolme_wave15_wrapper_family_matrix.json",
    "non_kolme_wave15_wrapper_family_baseline.json",
    "non_kolme_wave15_wrapper_family_trend_thresholds.json",
    "test_non_kolme_wave15_wrapper_family_baseline_contract.sh",
    "test_check_non_kolme_wave15_wrapper_family_budget_trend.sh",
    "check_non_kolme_wave15_wrapper_family_budget_trend.sh",
    "non_kolme_wave16_wrapper_family_matrix.json",
    "non_kolme_wave16_wrapper_family_baseline.json",
    "non_kolme_wave16_wrapper_family_trend_thresholds.json",
    "test_non_kolme_wave16_wrapper_family_baseline_contract.sh",
    "test_check_non_kolme_wave16_wrapper_family_budget_trend.sh",
    "check_non_kolme_wave16_wrapper_family_budget_trend.sh",
    "non_kolme_wave17_wrapper_family_matrix.json",
    "non_kolme_wave17_wrapper_family_baseline.json",
    "non_kolme_wave17_wrapper_family_trend_thresholds.json",
    "test_non_kolme_wave17_wrapper_family_baseline_contract.sh",
    "test_check_non_kolme_wave17_wrapper_family_budget_trend.sh",
    "check_non_kolme_wave17_wrapper_family_budget_trend.sh",
    "non_kolme_wave18_wrapper_family_matrix.json",
    "non_kolme_wave18_wrapper_family_baseline.json",
    "non_kolme_wave18_wrapper_family_trend_thresholds.json",
    "test_non_kolme_wave18_wrapper_family_baseline_contract.sh",
    "test_check_non_kolme_wave18_wrapper_family_budget_trend.sh",
    "check_non_kolme_wave18_wrapper_family_budget_trend.sh",
];

const DISPATCHER_MATRIX_MARKERS: &[&str] = &[
    "Non-Kolme bridge dispatcher wrapper-matrix guard stays on PR fast gate:",
    "test_non_kolme_bridge_contract_lane_dispatch_wrapper_matrix.sh",
    "Non-Kolme sdk dispatcher wrapper-matrix guard stays on PR fast gate:",
    "test_non_kolme_sdk_contract_lane_dispatch_wrapper_matrix.sh",
    "Non-Kolme lightweight dispatcher wrapper-matrix guard stays on PR fast gate:",
    "test_non_kolme_lightweight_contract_lane_dispatch_wrapper_matrix.sh",
    "Non-Kolme wave-10 lightweight dispatcher wrapper-matrix guard stays on PR fast gate:",
    "test_non_kolme_wave10_lightweight_contract_lane_dispatch_wrapper_matrix.sh",
    "Non-Kolme wave-11 lightweight dispatcher wrapper-matrix guard stays on PR fast gate:",
    "test_non_kolme_wave11_lightweight_contract_lane_dispatch_wrapper_matrix.sh",
    "Non-Kolme wave-12 lightweight dispatcher wrapper-matrix guard stays on PR fast gate:",
    "test_non_kolme_wave12_lightweight_contract_lane_dispatch_wrapper_matrix.sh",
    "Non-Kolme wave-13 lightweight dispatcher wrapper-matrix guard stays on PR fast gate:",
    "test_non_kolme_wave13_lightweight_contract_lane_dispatch_wrapper_matrix.sh",
    "Non-Kolme wave-14 lightweight dispatcher wrapper-matrix guard stays on PR fast gate:",
    "test_non_kolme_wave14_lightweight_contract_lane_dispatch_wrapper_matrix.sh",
    "Non-Kolme wave-15 lightweight dispatcher wrapper-matrix guard stays on PR fast gate:",
    "test_non_kolme_wave15_lightweight_contract_lane_dispatch_wrapper_matrix.sh",
    "Non-Kolme wave-16 lightweight dispatcher wrapper-matrix guard stays on PR fast gate:",
    "test_non_kolme_wave16_lightweight_contract_lane_dispatch_wrapper_matrix.sh",
    "Non-Kolme wave-17 lightweight dispatcher wrapper-matrix guard stays on PR fast gate:",
    "test_non_kolme_wave17_lightweight_contract_lane_dispatch_wrapper_matrix.sh",
    "Non-Kolme wave-18 lightweight dispatcher wrapper-matrix guard stays on PR fast gate:",
    "test_non_kolme_wave18_lightweight_contract_lane_dispatch_wrapper_matrix.sh",
];

#[test]
fn doc_contains_wrapper_family_wave_markers() {
    assert_doc_contains_all(WRAPPER_FAMILY_WAVE_MARKERS, "wrapper family wave");
}

#[test]
fn doc_contains_wrapper_family_tail_markers() {
    assert_doc_contains_all(WRAPPER_FAMILY_TAIL_MARKERS, "wrapper family tail");
}

#[test]
fn doc_contains_dispatcher_matrix_markers() {
    assert_doc_contains_all(DISPATCHER_MATRIX_MARKERS, "dispatcher matrix");
}
