[package]
name = "kamn-node"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "kamn-node"
path = "src/main.rs"

[dependencies]
kamn-core = { path = "../kamn-core" }
axum = { version = "0.8.8", features = ["ws"] }
futures-util = "0.3.31"
k256 = { version = "0.13.4", features = ["ecdsa"] }
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros", "net", "time", "signal"] }
zeroize = "1.8.2"

[lints]
workspace = true
