//! Bridge adapter contracts for inbound normalization and outbound translation.

use crate::{
    AgentDid, CanonicalMessageEnvelope, EnvelopeEncryption, EnvelopeHeader, EnvelopeMetadata,
    EnvelopeProof, CANONICAL_ENCRYPTION_ALGORITHM, CANONICAL_MESSAGE_ENVELOPE_TYPE,
    CANONICAL_PROOF_PURPOSE,
};
use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

const DEFAULT_MAX_INBOUND_AGE_SECS: u64 = 300;

/// Supported external bridge platforms.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum BridgePlatform {
    /// Telegram bridge surface.
    Telegram,
    /// Discord bridge surface.
    Discord,
    /// Slack bridge surface.
    Slack,
    /// Signal bridge surface.
    Signal,
    /// X/Twitter bridge surface.
    Twitter,
    /// Custom bridge surface identified by label.
    Custom(String),
}

impl BridgePlatform {
    fn label(&self) -> String {
        match self {
            Self::Telegram => "telegram".to_owned(),
            Self::Discord => "discord".to_owned(),
            Self::Slack => "slack".to_owned(),
            Self::Signal => "signal".to_owned(),
            Self::Twitter => "twitter".to_owned(),
            Self::Custom(name) => name.trim().to_lowercase(),
        }
    }
}

/// Direction of bridge traffic used by policy and audit surfaces.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BridgeDirection {
    /// External platform to KAMN ingress.
    Inbound,
    /// KAMN to external platform egress.
    Outbound,
}

/// Raw inbound message payload received from a bridge connector.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BridgeInboundEnvelope {
    /// Message ID provided by the external platform.
    pub external_message_id: String,
    /// Sender identifier provided by the external platform.
    pub external_sender_id: String,
    /// Source channel/thread identifier on the external platform.
    pub external_channel_id: String,
    /// Target KAMN agent DID to route the message to.
    pub target_agent_did: String,
    /// Message body payload.
    pub body: String,
    /// RFC3339 timestamp string emitted by the connector.
    pub received_at: String,
    /// Unix timestamp representation of `received_at`.
    pub received_at_unix: u64,
}

/// Canonical inbound shape produced by a [`BridgeAdapter`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NormalizedInboundMessage {
    /// Stable bridge-qualified message identifier.
    pub bridge_message_id: String,
    /// External sender handle.
    pub sender_handle: String,
    /// External source channel identifier.
    pub source_channel: String,
    /// Target KAMN agent DID.
    pub target_agent_did: String,
    /// Normalized message body.
    pub body: String,
    /// Canonicalized receive timestamp string.
    pub received_at: String,
    /// Canonicalized receive timestamp in Unix seconds.
    pub received_at_unix: u64,
    /// Originating bridge platform.
    pub platform: BridgePlatform,
}

/// Outbound request submitted for bridge delivery.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BridgeOutboundRequest {
    /// Idempotent request identifier generated by KAMN.
    pub request_id: String,
    /// DID of the sending KAMN agent.
    pub from_agent_did: String,
    /// External destination channel identifier.
    pub destination_channel_id: String,
    /// Outbound message body.
    pub body: String,
    /// RFC3339 creation timestamp.
    pub created_at: String,
}

/// Platform-ready outbound envelope emitted by a [`BridgeAdapter`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BridgeOutboundEnvelope {
    /// Outbound request identifier.
    pub request_id: String,
    /// External destination channel identifier.
    pub destination_channel_id: String,
    /// Serialized platform payload.
    pub payload: String,
    /// Target bridge platform.
    pub platform: BridgePlatform,
}

/// Adapter contract for platform-specific ingress/egress translation.
pub trait BridgeAdapter {
    /// Return the platform represented by this adapter.
    fn platform(&self) -> BridgePlatform;
    /// Return the bridge agent DID used for envelope provenance.
    fn bridge_agent_did(&self) -> &str;
    /// Normalize raw inbound bridge payload into canonical message shape.
    fn normalize_inbound(
        &self,
        inbound: &BridgeInboundEnvelope,
    ) -> Result<NormalizedInboundMessage, BridgeAdapterError>;
    /// Translate a canonical outbound request into platform payload.
    fn translate_outbound(
        &self,
        request: &BridgeOutboundRequest,
    ) -> Result<BridgeOutboundEnvelope, BridgeAdapterError>;
}

/// Policy hook contract for inbound and outbound authorization checks.
pub trait BridgePolicyHook {
    /// Authorize normalized inbound message processing.
    fn authorize_inbound(
        &self,
        normalized: &NormalizedInboundMessage,
    ) -> Result<(), BridgeAdapterError>;
    /// Authorize outbound request processing.
    fn authorize_outbound(&self, request: &BridgeOutboundRequest)
        -> Result<(), BridgeAdapterError>;
}

/// Permissive policy hook that authorizes all bridge traffic.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct AllowAllBridgePolicy;

impl AllowAllBridgePolicy {
    /// Construct an allow-all bridge policy hook.
    pub fn new() -> Self {
        Self
    }
}

impl BridgePolicyHook for AllowAllBridgePolicy {
    fn authorize_inbound(
        &self,
        _normalized: &NormalizedInboundMessage,
    ) -> Result<(), BridgeAdapterError> {
        Ok(())
    }

    fn authorize_outbound(
        &self,
        _request: &BridgeOutboundRequest,
    ) -> Result<(), BridgeAdapterError> {
        Ok(())
    }
}

/// Default adapter that passes fields through with deterministic normalization.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PassThroughBridgeAdapter {
    platform: BridgePlatform,
    bridge_agent_did: String,
}

impl PassThroughBridgeAdapter {
    /// Construct a pass-through adapter for a given platform and bridge DID.
    pub fn new(
        platform: BridgePlatform,
        bridge_agent_did: &str,
    ) -> Result<Self, BridgeAdapterError> {
        if platform.label().is_empty() {
            return Err(BridgeAdapterError::EmptyField("platform"));
        }
        validate_did(bridge_agent_did)?;
        Ok(Self {
            platform,
            bridge_agent_did: bridge_agent_did.to_owned(),
        })
    }
}

impl BridgeAdapter for PassThroughBridgeAdapter {
    fn platform(&self) -> BridgePlatform {
        self.platform.clone()
    }

    fn bridge_agent_did(&self) -> &str {
        &self.bridge_agent_did
    }

    fn normalize_inbound(
        &self,
        inbound: &BridgeInboundEnvelope,
    ) -> Result<NormalizedInboundMessage, BridgeAdapterError> {
        validate_inbound_envelope(inbound)?;

        Ok(NormalizedInboundMessage {
            bridge_message_id: format!("{}:{}", self.platform.label(), inbound.external_message_id),
            sender_handle: inbound.external_sender_id.clone(),
            source_channel: inbound.external_channel_id.clone(),
            target_agent_did: inbound.target_agent_did.clone(),
            body: inbound.body.clone(),
            received_at: inbound.received_at.clone(),
            received_at_unix: inbound.received_at_unix,
            platform: self.platform(),
        })
    }

    fn translate_outbound(
        &self,
        request: &BridgeOutboundRequest,
    ) -> Result<BridgeOutboundEnvelope, BridgeAdapterError> {
        validate_outbound_request(request)?;
        Ok(BridgeOutboundEnvelope {
            request_id: request.request_id.clone(),
            destination_channel_id: request.destination_channel_id.clone(),
            payload: format!(
                "{{\"platform\":\"{}\",\"channel\":\"{}\",\"message\":\"{}\"}}",
                self.platform.label(),
                escape_json(&request.destination_channel_id),
                escape_json(&request.body),
            ),
            platform: self.platform(),
        })
    }
}

/// Bridge orchestration engine that enforces policy, freshness, and replay guards.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BridgeAdapterEngine<A, P> {
    adapter: A,
    policy: P,
    max_inbound_age_secs: u64,
    seen_inbound_message_ids: RefCell<BTreeSet<String>>,
    seen_outbound_request_ids: RefCell<BTreeSet<String>>,
}

impl<A, P> BridgeAdapterEngine<A, P>
where
    A: BridgeAdapter,
    P: BridgePolicyHook,
{
    /// Build an engine using the default inbound freshness window.
    pub fn new(adapter: A, policy: P) -> Self {
        Self::with_inbound_freshness_window(adapter, policy, DEFAULT_MAX_INBOUND_AGE_SECS)
    }

    /// Build an engine with an explicit inbound freshness window in seconds.
    pub fn with_inbound_freshness_window(adapter: A, policy: P, max_inbound_age_secs: u64) -> Self {
        Self {
            adapter,
            policy,
            max_inbound_age_secs,
            seen_inbound_message_ids: RefCell::new(BTreeSet::new()),
            seen_outbound_request_ids: RefCell::new(BTreeSet::new()),
        }
    }

    /// Normalize and authorize inbound traffic with freshness and replay checks.
    pub fn process_inbound(
        &self,
        inbound: &BridgeInboundEnvelope,
        observed_at_unix: u64,
    ) -> Result<NormalizedInboundMessage, BridgeAdapterError> {
        validate_did(self.adapter.bridge_agent_did())?;
        validate_inbound_envelope(inbound)?;
        validate_timestamp("observed_at_unix", observed_at_unix)?;
        let normalized = self.adapter.normalize_inbound(inbound)?;
        validate_normalized_inbound(&normalized)?;
        self.policy.authorize_inbound(&normalized)?;
        let age_secs = observed_at_unix.saturating_sub(normalized.received_at_unix);
        if age_secs > self.max_inbound_age_secs {
            return Err(BridgeAdapterError::StaleInboundMessage {
                bridge_message_id: normalized.bridge_message_id.clone(),
                received_at_unix: normalized.received_at_unix,
                observed_at_unix,
                max_age_secs: self.max_inbound_age_secs,
            });
        }
        let bridge_message_id = normalized.bridge_message_id.clone();
        if !self
            .seen_inbound_message_ids
            .borrow_mut()
            .insert(bridge_message_id.clone())
        {
            return Err(BridgeAdapterError::DuplicateInboundMessageId(
                bridge_message_id,
            ));
        }
        Ok(normalized)
    }

    /// Authorize and translate outbound traffic with request-ID replay protection.
    pub fn process_outbound(
        &self,
        request: &BridgeOutboundRequest,
    ) -> Result<BridgeOutboundEnvelope, BridgeAdapterError> {
        validate_outbound_request(request)?;
        self.policy.authorize_outbound(request)?;
        let translated = self.adapter.translate_outbound(request)?;
        if translated.request_id != request.request_id {
            return Err(BridgeAdapterError::OutboundRequestIdMismatch {
                expected: request.request_id.clone(),
                actual: translated.request_id,
            });
        }
        validate_non_empty(
            "bridge_outbound_envelope.destination_channel_id",
            &translated.destination_channel_id,
        )?;
        validate_non_empty("bridge_outbound_envelope.payload", &translated.payload)?;
        if !self
            .seen_outbound_request_ids
            .borrow_mut()
            .insert(request.request_id.clone())
        {
            return Err(BridgeAdapterError::DuplicateOutboundRequestId(
                request.request_id.clone(),
            ));
        }
        Ok(translated)
    }

    /// Convert inbound bridge payload into a validated canonical message envelope.
    pub fn process_inbound_to_envelope(
        &self,
        inbound: &BridgeInboundEnvelope,
        observed_at_unix: u64,
        recipient_keys: Vec<String>,
        expires: &str,
        nonce: u64,
    ) -> Result<CanonicalMessageEnvelope, BridgeAdapterError> {
        if recipient_keys.is_empty() {
            return Err(BridgeAdapterError::EmptyField("recipient_keys"));
        }
        for key in &recipient_keys {
            validate_non_empty("recipient_keys[]", key)?;
        }
        validate_non_empty("expires", expires)?;
        if nonce == 0 {
            return Err(BridgeAdapterError::InvalidNonce(nonce));
        }

        let normalized = self.process_inbound(inbound, observed_at_unix)?;

        let mut body = BTreeMap::new();
        body.insert("message".to_owned(), normalized.body.clone());
        body.insert(
            "external_sender".to_owned(),
            normalized.sender_handle.clone(),
        );
        body.insert(
            "external_channel".to_owned(),
            normalized.source_channel.clone(),
        );
        body.insert("platform".to_owned(), normalized.platform.label());

        let envelope = CanonicalMessageEnvelope {
            envelope: EnvelopeMetadata {
                id: normalized.bridge_message_id.clone(),
                type_name: CANONICAL_MESSAGE_ENVELOPE_TYPE.to_owned(),
                from: self.adapter.bridge_agent_did().to_owned(),
                to: vec![normalized.target_agent_did.clone()],
                created: normalized.received_at.clone(),
                expires: expires.to_owned(),
                thread_id: None,
                parent_id: None,
                nonce,
            },
            header: EnvelopeHeader {
                message_type: "Request".to_owned(),
                priority: "normal".to_owned(),
                content_type: "application/json".to_owned(),
                encryption: EnvelopeEncryption {
                    algorithm: CANONICAL_ENCRYPTION_ALGORITHM.to_owned(),
                    recipient_keys,
                },
            },
            body,
            attachments: Vec::new(),
            proof: EnvelopeProof {
                type_name: "Ed25519Signature2020".to_owned(),
                created: normalized.received_at,
                verification_method: format!("{}#bridge-key-1", self.adapter.bridge_agent_did()),
                proof_purpose: CANONICAL_PROOF_PURPOSE.to_owned(),
                proof_value: format!("proof:{}", normalized.bridge_message_id),
            },
        };
        envelope
            .validate()
            .map_err(|error| BridgeAdapterError::Envelope(error.to_string()))?;
        Ok(envelope)
    }
}

/// Errors emitted by bridge adapter validation, policy, and conversion flows.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BridgeAdapterError {
    /// Inbound message ID was observed previously.
    DuplicateInboundMessageId(String),
    /// Outbound request ID was observed previously.
    DuplicateOutboundRequestId(String),
    /// A required field was empty after normalization.
    EmptyField(&'static str),
    /// DID failed canonical parsing/validation.
    InvalidDid(String),
    /// Timestamp value was invalid for the given field.
    InvalidTimestamp(&'static str),
    /// Envelope nonce must be positive.
    InvalidNonce(u64),
    /// Inbound message exceeded allowed freshness window.
    StaleInboundMessage {
        /// Qualified inbound message identifier.
        bridge_message_id: String,
        /// Original receive timestamp.
        received_at_unix: u64,
        /// Processing observation timestamp.
        observed_at_unix: u64,
        /// Maximum supported message age in seconds.
        max_age_secs: u64,
    },
    /// Policy hook rejected traffic in the given direction.
    PolicyDenied {
        /// Traffic direction denied by policy.
        direction: BridgeDirection,
        /// Human-readable policy denial reason.
        reason: String,
    },
    /// Adapter returned an outbound ID that does not match request ID.
    OutboundRequestIdMismatch {
        /// Request ID expected by engine.
        expected: String,
        /// Request ID returned by adapter.
        actual: String,
    },
    /// Canonical envelope validation failure.
    Envelope(String),
}

impl fmt::Display for BridgeAdapterError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::DuplicateInboundMessageId(message_id) => {
                write!(f, "duplicate inbound message id: {message_id}")
            }
            Self::DuplicateOutboundRequestId(request_id) => {
                write!(f, "duplicate outbound request id: {request_id}")
            }
            Self::EmptyField(field) => write!(f, "field must not be empty: {field}"),
            Self::InvalidDid(value) => write!(f, "invalid did: {value}"),
            Self::InvalidTimestamp(field) => write!(f, "timestamp must be > 0: {field}"),
            Self::InvalidNonce(value) => write!(f, "nonce must be greater than zero: {value}"),
            Self::StaleInboundMessage {
                bridge_message_id,
                received_at_unix,
                observed_at_unix,
                max_age_secs,
            } => write!(
                f,
                "stale inbound message: id={bridge_message_id}, received_at_unix={received_at_unix}, observed_at_unix={observed_at_unix}, max_age_secs={max_age_secs}"
            ),
            Self::PolicyDenied { direction, reason } => {
                write!(f, "policy denied {direction:?} traffic: {reason}")
            }
            Self::OutboundRequestIdMismatch { expected, actual } => write!(
                f,
                "outbound request id mismatch: expected {expected}, got {actual}"
            ),
            Self::Envelope(value) => write!(f, "invalid canonical envelope: {value}"),
        }
    }
}

impl std::error::Error for BridgeAdapterError {}

fn validate_inbound_envelope(inbound: &BridgeInboundEnvelope) -> Result<(), BridgeAdapterError> {
    validate_non_empty(
        "bridge_inbound_envelope.external_message_id",
        &inbound.external_message_id,
    )?;
    validate_non_empty(
        "bridge_inbound_envelope.external_sender_id",
        &inbound.external_sender_id,
    )?;
    validate_non_empty(
        "bridge_inbound_envelope.external_channel_id",
        &inbound.external_channel_id,
    )?;
    validate_did(&inbound.target_agent_did)?;
    validate_non_empty("bridge_inbound_envelope.body", &inbound.body)?;
    validate_non_empty("bridge_inbound_envelope.received_at", &inbound.received_at)?;
    validate_timestamp(
        "bridge_inbound_envelope.received_at_unix",
        inbound.received_at_unix,
    )?;
    Ok(())
}

fn validate_normalized_inbound(
    normalized: &NormalizedInboundMessage,
) -> Result<(), BridgeAdapterError> {
    validate_non_empty(
        "normalized_inbound_message.bridge_message_id",
        &normalized.bridge_message_id,
    )?;
    validate_non_empty(
        "normalized_inbound_message.sender_handle",
        &normalized.sender_handle,
    )?;
    validate_non_empty(
        "normalized_inbound_message.source_channel",
        &normalized.source_channel,
    )?;
    validate_did(&normalized.target_agent_did)?;
    validate_non_empty("normalized_inbound_message.body", &normalized.body)?;
    validate_non_empty(
        "normalized_inbound_message.received_at",
        &normalized.received_at,
    )?;
    validate_timestamp(
        "normalized_inbound_message.received_at_unix",
        normalized.received_at_unix,
    )?;
    if normalized.platform.label().is_empty() {
        return Err(BridgeAdapterError::EmptyField(
            "normalized_inbound_message.platform",
        ));
    }
    Ok(())
}

fn validate_outbound_request(request: &BridgeOutboundRequest) -> Result<(), BridgeAdapterError> {
    validate_non_empty("bridge_outbound_request.request_id", &request.request_id)?;
    validate_did(&request.from_agent_did)?;
    validate_non_empty(
        "bridge_outbound_request.destination_channel_id",
        &request.destination_channel_id,
    )?;
    validate_non_empty("bridge_outbound_request.body", &request.body)?;
    validate_non_empty("bridge_outbound_request.created_at", &request.created_at)?;
    Ok(())
}

fn validate_non_empty(field: &'static str, value: &str) -> Result<(), BridgeAdapterError> {
    if value.trim().is_empty() {
        return Err(BridgeAdapterError::EmptyField(field));
    }
    Ok(())
}

fn validate_did(value: &str) -> Result<(), BridgeAdapterError> {
    AgentDid::parse(value).map_err(|error| BridgeAdapterError::InvalidDid(error.to_string()))?;
    Ok(())
}

fn validate_timestamp(field: &'static str, value: u64) -> Result<(), BridgeAdapterError> {
    if value == 0 {
        return Err(BridgeAdapterError::InvalidTimestamp(field));
    }
    Ok(())
}

fn escape_json(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            _ => escaped.push(ch),
        }
    }
    escaped
}

#[cfg(test)]
mod tests {
    use super::{
        AllowAllBridgePolicy, BridgeAdapter, BridgeAdapterEngine, BridgeAdapterError,
        BridgeDirection, BridgeInboundEnvelope, BridgeOutboundEnvelope, BridgeOutboundRequest,
        BridgePlatform, NormalizedInboundMessage, PassThroughBridgeAdapter,
    };

    #[test]
    fn constructor_rejects_invalid_bridge_agent_did() {
        assert_eq!(
            PassThroughBridgeAdapter::new(BridgePlatform::Discord, "not-a-did"),
            Err(BridgeAdapterError::InvalidDid(
                "invalid agent did prefix: not-a-did".to_owned()
            ))
        );
    }

    #[test]
    fn process_outbound_rejects_request_id_mutation() {
        #[derive(Debug, Clone, Copy)]
        struct BadAdapter;

        impl BridgeAdapter for BadAdapter {
            fn platform(&self) -> BridgePlatform {
                BridgePlatform::Telegram
            }

            fn bridge_agent_did(&self) -> &str {
                "kamn:did:agent:bridge-telegram"
            }

            fn normalize_inbound(
                &self,
                inbound: &BridgeInboundEnvelope,
            ) -> Result<NormalizedInboundMessage, BridgeAdapterError> {
                Ok(NormalizedInboundMessage {
                    bridge_message_id: format!("telegram:{}", inbound.external_message_id),
                    sender_handle: inbound.external_sender_id.clone(),
                    source_channel: inbound.external_channel_id.clone(),
                    target_agent_did: inbound.target_agent_did.clone(),
                    body: inbound.body.clone(),
                    received_at: inbound.received_at.clone(),
                    received_at_unix: inbound.received_at_unix,
                    platform: self.platform(),
                })
            }

            fn translate_outbound(
                &self,
                request: &BridgeOutboundRequest,
            ) -> Result<BridgeOutboundEnvelope, BridgeAdapterError> {
                Ok(BridgeOutboundEnvelope {
                    request_id: format!("{}-mutated", request.request_id),
                    destination_channel_id: request.destination_channel_id.clone(),
                    payload: "{\"message\":\"x\"}".to_owned(),
                    platform: self.platform(),
                })
            }
        }

        let engine = BridgeAdapterEngine::new(BadAdapter, AllowAllBridgePolicy::new());
        let request = BridgeOutboundRequest {
            request_id: "req-1".to_owned(),
            from_agent_did: "kamn:did:agent:planner-1".to_owned(),
            destination_channel_id: "telegram:channel:a".to_owned(),
            body: "hi".to_owned(),
            created_at: "2026-02-08T09:00:00Z".to_owned(),
        };

        assert_eq!(
            engine.process_outbound(&request),
            Err(BridgeAdapterError::OutboundRequestIdMismatch {
                expected: "req-1".to_owned(),
                actual: "req-1-mutated".to_owned(),
            })
        );
    }

    #[test]
    fn process_inbound_to_envelope_rejects_empty_recipient_keys() {
        let adapter = PassThroughBridgeAdapter::new(
            BridgePlatform::Discord,
            "kamn:did:agent:bridge-discord-1",
        )
        .expect("adapter should be valid");
        let engine = BridgeAdapterEngine::new(adapter, AllowAllBridgePolicy::new());
        let inbound = BridgeInboundEnvelope {
            external_message_id: "ext-9".to_owned(),
            external_sender_id: "discord:user-1".to_owned(),
            external_channel_id: "discord:channel:1".to_owned(),
            target_agent_did: "kamn:did:agent:planner-1".to_owned(),
            body: "hello".to_owned(),
            received_at: "2026-02-08T09:00:00Z".to_owned(),
            received_at_unix: 1_707_383_600,
        };

        assert_eq!(
            engine.process_inbound_to_envelope(
                &inbound,
                1_707_383_600,
                Vec::new(),
                "2026-02-08T10:00:00Z",
                1,
            ),
            Err(BridgeAdapterError::EmptyField("recipient_keys"))
        );
    }

    #[test]
    fn process_inbound_rejects_duplicate_message_id() {
        let adapter = PassThroughBridgeAdapter::new(
            BridgePlatform::Discord,
            "kamn:did:agent:bridge-discord-1",
        )
        .expect("adapter should be valid");
        let engine = BridgeAdapterEngine::new(adapter, AllowAllBridgePolicy::new());
        let inbound = BridgeInboundEnvelope {
            external_message_id: "ext-9".to_owned(),
            external_sender_id: "discord:user-1".to_owned(),
            external_channel_id: "discord:channel:1".to_owned(),
            target_agent_did: "kamn:did:agent:planner-1".to_owned(),
            body: "hello".to_owned(),
            received_at: "2026-02-08T09:00:00Z".to_owned(),
            received_at_unix: 1_707_383_600,
        };

        assert!(engine.process_inbound(&inbound, 1_707_383_700).is_ok());
        assert_eq!(
            engine.process_inbound(&inbound, 1_707_383_700),
            Err(BridgeAdapterError::DuplicateInboundMessageId(
                "discord:ext-9".to_owned()
            ))
        );
    }

    #[test]
    fn process_outbound_rejects_duplicate_request_id() {
        let adapter = PassThroughBridgeAdapter::new(
            BridgePlatform::Discord,
            "kamn:did:agent:bridge-discord-1",
        )
        .expect("adapter should be valid");
        let engine = BridgeAdapterEngine::new(adapter, AllowAllBridgePolicy::new());
        let request = BridgeOutboundRequest {
            request_id: "req-1".to_owned(),
            from_agent_did: "kamn:did:agent:planner-1".to_owned(),
            destination_channel_id: "discord:channel:1".to_owned(),
            body: "hello".to_owned(),
            created_at: "2026-02-08T09:00:00Z".to_owned(),
        };

        assert!(engine.process_outbound(&request).is_ok());
        assert_eq!(
            engine.process_outbound(&request),
            Err(BridgeAdapterError::DuplicateOutboundRequestId(
                "req-1".to_owned()
            ))
        );
    }

    #[test]
    fn display_policy_denied_error_mentions_direction() {
        let error = BridgeAdapterError::PolicyDenied {
            direction: BridgeDirection::Inbound,
            reason: "blocked".to_owned(),
        };
        assert_eq!(error.to_string(), "policy denied Inbound traffic: blocked");
    }
}
